= Koji databases
:page-slug: koji-database
:page-description: How to use the built-in Koji database in your apps.

Each Koji project includes a key-value storage structure that you can use as a backend database for simple use cases, such as collecting information from users, aggregating survey or poll results, and creating leaderboards for games.

* A Koji database is comprised of one or more [.term]#collections#.
* A collection is comprised of related database records.
* A database record must have a unique name (used as the primary key) and is comprised of a set of key-value pairs.
* A value can be of any type, including strings, numbers, and arrays.

For example:

[singlespaced]
* A leaderboard database for a game app could have a collection called "top10".
* The collection could have up to 10 database records.
* For each record, the username could be the unique key and could include key-value pairs with the following keys:
+
** highest-score
** date-of-highest-score

An app can view, download to CSV, or delete data from any collection in its own database.
Additionally, you can create custom database views to simplify content moderation and data collection for the app owner.
These views are also used in the *Database* section of the debugger.

== Using a Koji database

To use a Koji database in your project,

. Install and import the @withkoji/core package in the backend of your Koji project. <<app-dev-process#_add_withkojicore_to_the_backend,Learn how.>>

. Collect data in the frontend. <<capture-user-input#,Learn how.>>

. Use the <<core-backend-database#Constructor#,KojiBackend.Database>> class to manage the data in the Koji database.
+
** `.get` – Retrieves a collection or an record.
[.apiref]#<<core-backend-database#get,API reference>>#

** `.getAll` – Retrieves the specified records.
[.apiref]#<<core-backend-database#getAll,API reference>>#

** `.getWhere` – Retrieves all records that meet a condition where the value of a key is compared with a single specified string.
[.apiref]#<<core-backend-database#getWhere,API reference>>#

** `.getAllWhere` – Retrieves all records that meet a condition where the value of a key is compared with one or more values in the specified array.
[.apiref]#<<core-backend-database#getAllWhere,API reference>>#

** `.getCollections` – Returns the list of all collections in the database.
[.apiref]#<<core-backend-database#getCollections,API reference>>#

** `.search` – Retrieves all records where the value of the specified key is equal to the specified search value.
[.apiref]#<<core-backend-database#search,API reference>>#

** `.set` – Adds an record to the Koji database.
[.apiref]#<<core-backend-database#set,API reference>>#

** `.update` – Modifies the specified record if one exists with the specified name.
Otherwise, creates a new record.
[.apiref]#<<core-backend-database#update,API reference>>#

== Customizing database views

You can define one or more database views, which are tables in which to display the contents of the database.

Database view definitions must be in the `koji.json` file inside the `database` node, which is at the same level as the `develop` node.

.Database view definitions in koji.json
[source,JSON]
----
{
  ...
  "develop": {
    "frontend": {
      ...
    },
    "backend": {
      ...
    }
  },
  "database": {
    "views": [
      {
        "name": "Top 10 Leaderboard",  <1>
        "collection": "top10",  <2>
        "columns": [ <3>
          {
            "key": "userId",  <4>
            "name": "User",  <5>
            "type": "string"  <6>
          },
          {
            "key": "highscore",  <4>
            "name": "Highest Score",  <5>
            "type": "number"  <6>
          }
        ],
        "sort": { <7>
          "key": "highscore",  <8>
          "direction": "desc"  <9>
        }
      },
      {
        ...
      }
    ]
  }
}
----
<1> `name` – User-friendly name for the view.
<2> `collection` – The collection to which the view applies.
<3> `columns` – An array of columns to display in the database view.
The order of the columns in the array is also the order the columns are displayed in the view.
<4> `columns.key` – The key associated with the value to display in the column.
<5> `columns.name` – The user-friendly name for the column in the database view.
<6> `columns.type` – The data type of the value to display.
Defines how the data appears in the view.
Supported types are: `string` (default), `image`, `link`, `number`, `date` (Unix timestamp), `object`, and `boolean`.
If a database view is not defined in the project, all data is displayed as strings.
<7> `sort` – The default sort of the view.
<8> `sort.key` – The key used as the sort index.
<9> `sort.direction` – The order in which to sort the data, `asc` (ascending) or `desc` (descending).

== Viewing and managing the data

When developing an app, you can use the Koji debugger to test the data collection logic and the database view configuration.
When you publish your own app or customize someone else's app, you can access the data from the app.

* To test your database implementation, open the Koji debugger.
In the *Database* panel, select the collection you want to view.
For more information, see <<testing-apps#_debugging_database_views>>.

* To access the raw data for a Koji you created, go to menu:App[... > Database].

== Related resources

* <<core-backend-database#,Backend.Database reference>>
* <<add-service#>>
