= Thumbnail image and custom metadata
:page-slug: thumbnail-image
:page-description: How to customize the thumbnail (Open Graph) image and metadata for your Koji app.
:page-banner: {imagesDir}/Koji-screenshot=1.png

When you share a Koji app on social media, the Koji platform renders a thumbnail (Open Graph) image based on a screenshot of the app.
If you were designing a webpage from scratch, you would use meta tags to set properties for the thumbnail, such as `og:image`, `og:title`, and `og:description`.
The Koji platform automatically sets these properties for you, but you can override some of Koji's default settings to provide a customized thumbnail.

By default, the platform takes a screenshot of the initial view.
In some cases, the initial view might not be the best preview image for your app.
For example, if a game app starts with an instruction screen, a screenshot of the first level might provide a better preview image.
To improve the sharing experience in these cases, you can render a custom view of your app that is designed specifically to make an impression when sharing an app.
You can also control the timing of the screenshot to ensure that all relevant assets have loaded before the preview image is generated.

You can also customize the thumbnail metadata by configuring an entitlement.

== Customizing the thumbnail

To customize the thumbnail for your app, render a custom view when the URL contains the `Koji.playerState.context=screenshot` query parameter.
For optimal thumbnail support, design this view with the following considerations in mind.

* The image is responsive.
* The image looks good with a square aspect ratio.
* The image is optimized for faster loading.
For example, to reduce the image size to 400x400 pixels and load only the first frame of a gif, you can add query parameters at the end of your image's URL: `\https://images.koji-cdn.com/path/to/myimage.gif?fit=bounds&width=400&height=400&frame=1`
* The image includes customizable elements to generate unique previews for each customized version of the app.

image::Koji-screenshot=1.svg[Render a view for the thumbnail image]

For the following example, assume the app supports customizing the title, font size, and logo.

. In your application code, add a conditional statement to display a different image for social shares.
For example:
+
[source,JavaScript]
----
render() {
  if (window.location.search.includes('Koji.playerState.context=screenshot')) {
    return (
      <SocialSharePreview>
          <H1
          fontSize={this.state.titleOptions.fontSize}
          >{this.state.titleOptions.title}</H1>
          <Image src={this.optimizeURL(this.state.logo)} />
        </SocialSharePreview>
    );
  }
  ...
}
----

. Define appropriate styles for the thumbnail image.
+
To ensure that it is displayed correctly, design the thumbnail image as a responsive square.
+
[source,JavaScript]
----
const SocialSharePreview = styled.div`
  background-color: #395b88;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  text-align: center;
  color: #fcfcfc;
`;
----

. To test the preview image, open your staging link and append `?Koji.playerState.context=screenshot` to the URL.

== Controlling the screenshot timing

The Koji platform uses the `window.kojiScreenshotReady` property to determine the timing of the thumbnail screenshot.

When the platform loads a template, it checks for `window.kojiScreenshotReady = false;`.
If this value isn't present, the platform takes the screenshot right away.
If it is, the platform sets an interval to check the value every 100ms.
When the value changes to `true` or a maximum interval of 2000ms elapses, the platform takes the screenshot.

This feature enables you to ensure that the relevant fonts, images, videos, and other assets have loaded before the sharing image is generated.
For example:

. In the `index.html` file, add the following script tag.
+
[source, HTML]
<script> window.kojiScreenshotReady = false; </script>

. In your application code, add the following code after confirming that the relevant assets have loaded.
[source, JavaScript]
window.kojiScreenshotReady = true;

== Customizing the thumbnail metadata

To enable custom metadata when sharing a Koji app on social media, configure the `CustomMetadata` object in the `.koji/project/entitlements.json` file.

[source,JSON]
----
{
  "entitlements": {
    "CustomMetadata": {
      "enabled": true, <1>
      "metadata": {
        "title": "{{settings.title}}", <2>
        "description": "{{settings.description}}" <3>
      }
    }
  }
}
----
<1> `enabled` – Whether to use custom metadata when a creator shares a customization of the app.
<2> `metadata.title` – Path to the Visual Customization Control (VCC) that defines the title, if custom metadata is enabled.
<3> `metadata.description` – Path to the VCC that defines the description, if custom metadata is enabled.
