= @withkoji/custom-vcc-sdk
:page-slug: withkoji-custom-vcc-sdk
:page-description: Package for implementing custom controls that capture user input on the frontend of your Koji template.

The @withkoji/custom-vcc-sdk package enables you to
//tag::description[]
implement custom controls for capturing user input on the frontend of your Koji template.
//end::description[]

The Koji platform includes controls for standard elements, such as images, text, and sounds.
With this package, you can build custom controls that match closely with the application you are developing.
For example, some Koji templates provide tile map editors, sound enhancers, or custom avatar creators to enhance the interactivity for remixers.

== Installation

Install the package in your Koji project.

[source,bash]
npm install --save @withkoji/custom-vcc-sdk

== Basic use

=== Building custom controls

Import and instantiate CustomVcc.

[source,JavaScript]
----
import CustomVcc from '@withkoji/custom-vcc-sdk'
const customVcc = new CustomVcc();
----

Assign event listeners for updates.

[source,JavaScript]
----
customVcc.onTheme((theme) => {
  // Listen to Koji theme to match the styles in your control
});

customVcc.onUpdate((props) => {
  // Listen to the control's current state
});
----

When the custom control has loaded, register it to trigger events from the parent editor.

[source,JavaScript]
customVcc.register(width, height);

When a user changes the value, update it and save the file.

[source,JavaScript]
----
customVcc.change(newValue);
customVcc.save();
----

=== Using custom controls

To make a custom control accessible to Koji templates, you must serve it at a custom domain.
After you publish the project, add a subdomain under the `koji-vccs.com` root domain.

Then, you can use the control in a Koji template in one of these ways.

* (Recommended) With the @withkoji/core package, call the `Koji.ui.capture.custom` method with the subdomain name.
For example:
+
`const music = await Koji.ui.capture.custom({ name: 'scloud' });`
* (Deprecated) With the @withkoji/vcc package, use the subdomain name as the VCC type.
For example:
+
`"type": "custom<YOUR-SUBDOMAIN-NAME>"`

== Related resources

* https://github.com/madewithkoji/koji-custom-vcc-sdk[@withkoji/custom-vcc-sdk on Github]
* https://www.npmjs.com/package/@withkoji/custom-vcc-sdk[@withkoji/custom-vcc-sdk on npm]
* <<build-custom-vcc#>>
