= Programs
:page-slug: /getting-started/programs

At Koji, we want to enable everyone to create amazing, interactive content, and we need help from developers like you to make it happen.
That's why we are always looking for ways to better support and compensate developers for their hard work and ingenuity.

== Commissioned Template & Innovation Award Update (May 2020)

As of May 2020, we are sunsetting the Commissioned Template and Innovation Award programs.
These programs have been a great success, thanks to the Koji developer community, but no longer align with our current priorities.
Moving forward, we will be working on new programs that better support our goals as well as the developer community.

=== Commissioned Template Sunset Details

Developers with existing Commissioned Template assignments will be able to submit their work through the end of May 2020.
No new assignments will be given moving forward.

=== Innovation Award Sunset Details

To allow for any work in progress, we will be accepting submissions for the Innovation Award program through May 8, 2020.

== Future Programs

We are working on new programs to compensate developers for templates that reflect our current priorities.
We will share the details of these programs, here and on our https://discord.gg/eQuMJF6[Discord community], as soon as they are available.
