= App development process
:page-slug: app-dev-process
:page-description: Overview of how to develop a Koji app, from forking an existing app, to making your app customizable and enabling platform features, to deploying, testing, and distributing it.
:includespath: ../_includes

The Koji platform is designed for developers like you to build and distribute customizable web apps for content creators.
On Koji, creators can discover your apps, and then add them to their Link in Bio profiles and share them on social media.
As more creators use your Koji apps, you can make more revenue, reach more users, and build your business.

The following steps describe the general process for developing a customizable app on Koji and distributing it to content creators.

== [.callout1]#Choose a starting point#

A good starting point will provide a foundation that lets you start coding your app's unique features more quickly.
For example, you might start from a https://withkoji.com/create/for-developers[developer scaffold] that implements your favorite JavaScript framework, or from an app that already uses some desired functionality, such as a backend database.

. To create a new project, fork an existing app that allows developers to fork it.

.. In the App Store, find your desired starting app and click btn:[View].
+
TIP: To explore the source code for an app before forking it, click menu:...[Advanced Details > Source Code].
If this option is not available, the app does not allow developers to fork it.

.. In the app's detail page, click menu:...[Fork].
+
A copy of the project is created in your Koji account.

. Decide how you want to edit your code.
* *Online* – The Koji code editor is a browser-based integrated development environment (IDE) with built-in development, administration, and testing tools for Koji apps.
Learn more: <<editor#>>
* *Locally* – The Koji platform supports working locally in your preferred suite of development tools.
Learn more: <<local-development#>>

== [.callout2]#Develop your app#

At their core, Koji apps are full-stack, modern JavaScript applications.
They are designed to run in webviews, so that they are instantly available on all social platforms and every device.

The <<withkoji-koji-core#,@withkoji/core package>> enables apps to use core features of the Koji platform, so you can build any type of web application and enable creators to customize it.

=== Define configuration data

In your application code, you must initialize the @withkoji/core package with the configuration data that the Koji platform needs to build, deploy, and run your app.
To define this data, most Koji projects include a `koji.json` file at the root of the project directory.

. Define the instructions for building your code and deploying your app on the Koji platform.
Learn more: <<projects#develop, develop key>>, <<projects#deploy, deploy key>>

. If the app has customizable options for creators, define the default values for those options and any placeholder values for new, customized versions.
Learn more: <<projects#remixData, remixData key>>, <<projects#@@initialTransform, @@initialTransform key>>

. Configure the entitlements for the Koji platform features in your app.
Learn more: <<entitlements#>>

=== Develop the frontend

. Install or update the @withkoji/core package.
. Import and initialize in your code
. Add functionality (make it configurable)
. Koji.ready

=== Develop the backend

. Install
. Bundle koji.json
. Import
. Middleware
. Add functionality

== [.callout3]#Deploy your app#

Publish from the editor or push locally

Decide whether it's open-source

== [.callout4]#Test your app#



== [.callout5]#Distribute your app#

== Next steps
