= The Koji debugger
:page-slug: debugger
:page-description: Guide for the Koji debugger, a browser-based debugger for your published Koji.

The Koji debugger is a browser-based debugger for troubleshooting your Koji.
The debugger is only available after you publish your Koji for the first time.
To display the Koji debugger, click *Open debugger*.

== Overview

The Koji debugger is divided into two main sections:

* The *Context pane* -- Displays controls for a selected <<testing-templates#_using_live_previews, context>>. 
* The *Features pane* -- Displays controls related to any features that you implemented in your Koji.

=== The Context pane

A set of tabs above the *Context pane* allow you to select the context you want to display.
For example, if you select *Remix*, tools for viewing and changing specific elements of your Koji will be displayed.

The following contexts are available for selection:

* *Default* - Shows a preview of the running Koji and displays events generated by the Koji as they occur.
* *Remix* - Displays a special remixing page if you defined one.
Otherwise, it displays the editable elements of your Koji and allows you to change them. 
A second pane displays the VCC Values as they appear in the code for the Koji.
A third pane displays remix events as they occur.
* *Thumbnail* - 
* *Admin* -
* *About* - 
* *Sticker* -
* *Dynamic Receipt* -

=== The Features pane

