= The Koji debugger
:page-slug: debugger
:page-description: Guide for the Koji debugger, a browser-based debugger for your published Koji.

The Koji debugger is a browser-based debugger for troubleshooting your Koji.
The debugger is only available after you publish your Koji for the first time.
To display the Koji debugger, click *Open debugger*.

== Overview

The Koji debugger is divided into two main sections:

* The *Context pane* -- Displays controls for a selected <<testing-templates#_using_live_previews, context>>. 
* The *Info and Features pane* -- Displays controls related to environment info and implemented features.

=== The Context pane

A set of tabs allow you to select the context you want to display.
For example, if you select *Remix*, tools for viewing and changing specific elements of your Koji will be displayed.

Any context can be selected, whether or not it is enabled for your Koji.
If you select a context that is not enabled, a message will be displayed saying that it is unavailable.
The following contexts are available for selection:

* *Default* - Shows a preview of the running Koji and displays events generated by the Koji as they occur.
* *Remix* - Displays a special remixing page in a pane, if you defined such a page.
Otherwise, it displays the editable elements of your Koji and allows you to change them. 
A second pane displays the VCC Values as they appear in the code for the Koji.
A third pane displays remix events as they occur.
* *Thumbnail* - Displays square and rectangular previews of what your Koji will look like on social media.
* *Admin* - Displays a special admin page, if you defined one.
* *About* -  Displays a page that appears when the user clicks *Remix this Koji*, if you defined such a page.
* *Sticker* - Displays a page for an embedded Koji, if one exists.
* *Dynamic Receipt* - Displays a page where you can edit a dynamic receipt, if a dynamic receipt is defined. See <<withkoji-koji-iap-package, in-app purchases>>.

=== The Info and Features pane

You can view and modify environment info for your Koji and settings for implemented features.
If try to view settings for a feature that is not implemented, a message will display saying that no data was found for the feature.
The *Info and Features pane* includes these panels:

* *Environment info* - Displays your Koji's *App Id*, frame URL, and *VCC editor source*. Allows you to edit the frame URL and the VCC editor values.
* *Database* - Displays data from the Koji database.
* *In-app purchase receipts* - Displays receipts from *in-app purchases*.
* *Auth grants* - Displays authorization grants.
