= Porting existing code to Koji
:page-slug: /docs/develop/port-existing-code

In this tutorial, you will port an existing game to Koji.
You will make some updates to the game to make it customizable, and then you will build and deploy the game to the Koji platform.

Time: You should be able to complete this tutorial in 30 minutes or less.

== Prerequisites

Familiarity with the Koji editor, remix process, @withkoji/vcc package, and basic git commands.

== Starting from a scaffold

Because every application on Koji is a remix, you will want to find a "good" place to start from.
There are scaffolds for many existing game and application frameworks, including Phaser, P5, and React.

In this case, you will be working with a vanilla JS game, so you will use an even simpler starting point.

All games and applications on Koji need to be "built" for production, meaning that they need to be compiled into assets that can be bundled and served statically.
One solution that is very good at doing that is Webpack.

Webpack enables you to create a hot-reloading development environment, and build your game for production, as well.
It also allows for transpiling of advanced JS features using babel.
The trickiest part about webpack is configuring it properly.
Fortunately, there is a scaffold that has already done that for you.

. Remix this "Simple Webpack Scaffold":
+
https://withkoji.com/~seane/simple-webpack-scaffold
. Verify that the project is working.
.. Open *Customization > App settings* on the left side of the editor.
.. Change the "Hello, world!" value to something else.
+
If everything is working correctly, you should see the preview on the right update automatically with your new value.

== Bringing in existing code

There are many ways to bring existing code into your project.
If you have private files to import, you could share them using a service and bring them in with something like wget.

For this example, you will import files from a public git repository: https://github.com/arist0tl3/HTML5-Asteroids.

This repository is a fork of a basic Asteroids clone made in vanilla JS: http://www.dougmcinnes.com/2010/05/12/html-5-asteroids.

. Cancel the running npm command by clicking the "frontend" terminal at the bottom of the editor, and pressing *Ctrl+C*.
. Clone the Asteroids repo into a temp folder.
[source,bash]
git clone https://github.com/arist0tl3/HTML5-Asteroids temp
. Go to the temp folder, and move the important files into the parent folder.
+
[source,bash]
----
cd temp
mv game.js index.html ipad.js jquery-1.4.1.min.js vector_battle_regular.typeface.js ../
----
. Go back to the parent folder, and remove the temporary folder.
+
[source,bash]
----
cd ..
rm -rf temp
----
. Replace the existing `index.js` file with the new `game.js` file.
[source,bash]
rm index.js && mv game.js index.js
. Run the start command, to refresh the preview and see the Asteroids game.
[source,bash]
npm start

== Making a remixable template

By design, every application and game on Koji is remixable.
You can click the "Remix" button to create a forked version of the original.

In this example, you will take things one step further, by leveraging one of the most powerful tools on the platform: Visual Customization Controls (VCCs).

VCCs enable other people who remix your game or application to change things, without looking at one line of code.
Another way to think about this is "theming" or "reskinning" an application -- the underlying code isn't changing, just the assets.

Let's say you want to make the background color of the game customizable.
You need to do two things: set up a VCC to handle the user input, and consume the value inside the application.

. To set up the VCC, open *Customization > App settings* on the left side of the editor, and then click *Code* view at the top of the file.
. Paste the following code into the file, and then press *Ctrl+S* to save the file.
+
[source,json]
----
{
  "settings": {
    "backgroundColor": "#ffffff"
  },
  "@@editor": [
    {
      "key": "settings",
      "name": "App settings",
      "icon": "⚙️",
      "source": "settings.json",
      "fields": [
        {
          "key": "backgroundColor",
          "name": "Background Color",
          "type": "color"
        }
      ]
    }
  ]
}
----
+
This code replaces the existing values because that value won't be used in the application.
+
If you switch to the *Visual* view at the top of the file, you'll now see that the editor has rendered a color picker so that the user can choose a new background color.
+
If you change the background color, however, you will notice that nothing happens in the application.
You need to set up the application to consume that value, which you can do with the @withkoji/vcc package.
+
[NOTE]
====
This package has already been installed in this application. If you need to use it in another project, run:

`npm install @withkoji/vcc`
====
+
Because this project is written in vanilla JS, you can use simple dom manipulation to change the background color.
. Open the `frontend/index.html` file.
+
Notice the canvas element, with an `id` of `canvas`. You will target this element for the background color.
. Open the `frontend/index.js` file, and add the following code to the top of the file, below the initial comment:
+
[source,javascript]
----
const Koji = require('@withkoji/vcc').default;

const canvas = document.getElementById('canvas');
if (canvas) {
    canvas.style.background = Koji.config.settings.backgroundColor;
}
----
+
This code imports the default export from the @withkoji/vcc package, finds the canvas element, and assigns a value that is pulled from the configuration files.
. Refresh your application.
+
You should now see the correct background color. If you return to the App settings customization, changing the background color should also update your preview automatically.

== Publishing your template

Because this project is compiled with Webpack, you must `require` the local JS files, instead of referencing them in the `index.html` file.

. Open the `frontend/index.html` file, and remove the `<script>` tags from the top of the file.
+
There should be four of them.
. Press *Ctrl+S* to save the file.
. Open the `frontend/index.js` file, and add the following code above the block of code you pasted in the previous section:
+
[source,javascript]
----
require('jquery-1.4.1.min.js');
require('vector_battle_regular.typeface.js');
require('ipad.js');
----
. Press *Ctrl+S* to save the file, and make sure the preview is still working.
. When you are ready to see a live build of your project, click *Publish now* on the left side of the editor.
+
You will be prompted to enter additional information about your application, such as the name and description.
. Click *Publish*.
+
Publishing runs the build commands specified for the project, and then displays a live link to your production template.

== Adding sound effects

After your template has been published, you can enhance it by adding sound effects.
When you moved files from the original Asteroids repo into your project, the `.wav` files were not included.
That's because you will allow users to customize those sounds.

. Open the *App settings* customization, and open  the *Code* view.
. Replace the contents with the following code.
+
[source,json]
----
{
  "settings": {
    "backgroundColor": "#d3c1c1",
    "laserSound": "",
    "explosionSound": ""
  },
  "@@editor": [
    {
      "key": "settings",
      "name": "App settings",
      "icon": "⚙️",
      "source": "settings.json",
      "fields": [
        {
          "key": "backgroundColor",
          "name": "Background Color",
          "type": "color"
        },
        {
          "key": "laserSound",
          "name": "Laser Sound",
          "type": "sound"
        },
        {
          "key": "explosionSound",
          "name": "Explosion Sound",
          "type": "sound"
        }
      ]
    }
  ]
}
----
. Press *Ctrl+S* to save the file, and then return to the *Visual* view.
+
You should now see two additional pickers that allow a user to choose sounds for your game.
. Open the `frontend/index.js` file, and press *Ctrl+F* to open the finder tool.
. Enter `.wav` to search for the wav files that the game is using.
. Replace the block of code you found with the following code.
+
[source,javascript]
----
SFX = {
  laser:     new Audio(Koji.config.settings.laserSound),
  explosion: new Audio(Koji.config.settings.explosionSound),
};
----
. Press *Ctrl+S* to save the file.
+
The application now references the user-selected values for those sounds.
You can return to the *App settings* configuration, and use the sound pickers to replace these sounds with whatever you want.
You can even try just recording some sounds yourself.
For example, you can try "pew" for the laser and "pow!" for the explosion.
+
Changes to the sound choices should trigger a refresh of your application, and you should be able to hear the new sounds.
. Publish your changes to release an updated version of your template.

== Wrapping up

Hopefully, this tutorial has given you a better understanding of how to bring existing code onto the Koji platform, and integrate it with the tools that make Koji awesome.
