= Project structure and configuration
:page-slug: projects
:page-description: Description of the directory structure, files, and configuration data in a development project that power the features of a Koji app.

A repository on Koji contains everything that defines your development project, including the source code, assets, and configuration data.
This topic describes a typical repository structure and defines the configuration data that is required to develop and build apps on Koji.

////
As you develop the logic for your app, you must consider what additional features to offer, and then design experiences for different types of users and the different ways they might use it.
This topic provides an overview of the available platform features for a Koji app and a description of the required files and configuration data that power them.

Koji provides you with an environment for developing and publishing an application in your browser.
The project environment includes a terminal connected to a running container with all the familiar tools, a code editor, and tools to help you deploy your application.
////

== Source control on Git

The Koji platform uses Git repositories for source control.
A project directory on the Koji CDN stores the underlying files for each project.
When you start a new project by forking a scaffold or another app, the Koji platform creates a clone of its underlying repository.

Your new project directory is associated with the following Git repositories.

* `origin` – The Git repository for your new project.
Your app is built and deployed from this repository.
To work locally, you can clone the repository and push changes to it.
* `upstream` – The Git repository from which your project was forked.
To propose changes to the app you forked, you can create pull requests for this repository.

If you open your project in the Koji code editor, the development environment includes the project directory at `/usr/src/app` and Git remotes for these repositories.
To see the remotes, you can open a terminal tab and run `git remote -v`.

[source,console]
----
root@c8ce449b5538:/usr/src/app# git remote -v
origin  https://projects.koji-cdn.com/8a129043-4c22-4be7-875f-38b422008695.git (fetch)
origin  https://projects.koji-cdn.com/8a129043-4c22-4be7-875f-38b422008695.git (push)
upstream        https://projects.koji-cdn.com/e4d6b4bf-781a-4a49-9f0f-1d9cf3bbb7ff.git (fetch)
upstream        https://projects.koji-cdn.com/e4d6b4bf-781a-4a49-9f0f-1d9cf3bbb7ff.git (push)
----

== Directory structure and contents

A typical Koji project contains the `koji.json` configuration file and a README file at the root of the project directory, along with a directory for each service.

For example:

[source,console]
----
backend
├── src
├── package-lock.json
├── package.json
frontend
├── src
├── package-lock.json
├── package.json
koji.json
README.md
----

== Configuration data (koji.json)

The `koji.json` file defines the instructions for building and deploying your app on the Koji platform.
It also defines the settings that are required for certain platform features.
To implement these platform features in your app, you initialize the @withkoji/core package with the configuration data in the `koji.json` file.

=== develop

The `develop` key defines the configuration instructions for a development environment, such as the Koji code editor.

For each service in your app, specify the following properties:

* `path` – Source code directory for the service.
* `port` – Port on which the development server will run.
* `startCommand` – Script, defined in the `package.json` file of the service, that initiates a development build.

For example, this development configuration defines a frontend and backend service.

[source,JSON]
----
include::../_includes/koji.json[tag=develop,indent=0]
----

=== deploy

The `deploy` key defines the configuration instructions for a production deployment of your app.

For each service in your app, specify the following properties:

* `output` – Directory where your files will be compiled after the build commands are run.
* `type` – One of the following: `static` if the service deploys a static bundle (HTML, CSS, JS) or `dynamic` if the service deploys a server.
* `commands` – Steps to build your project.

For example, this deployment configuration defines a static frontend and a dynamic backend service.

[source,JSON]
----
include::../_includes/koji.json[tag=deploy,indent=0]
----

=== entitlements

The `entitlements` key enables and configures the Koji platform features that are implemented in your app.

=== remixData

//the `remixData` key initializes a dynamic data object
If you provide configuration options for creators who use your app, the `remixData` key defines the default values for those settings.
To manage remix data in your app, you use the <<core-frontend-remix#, Remix class>> in the @withkoji/core package.
To provide placeholder values when creators first open the settings, use the `@@initialTransform` key.

For example, this app has a default background color and title that creators can change.

[source,JSON]
----
include::../_includes/koji.json[tag=remixData,indent=0]
----

=== @@initialTransform

If you provide configuration options for creators who use your app, the `@@initialTransform` key defines placeholder values to use when a creator first opens these settings.
If a placeholder value is not specified, the default values in the `remixData` key are used.

For example, this app resets the title to a placeholder value when creators first configure it.

[source,JSON]
----
include::../_includes/koji.json[tag=initialTransform,indent=0]
----

=== metadata

The `metadata` key can define optional metadata about the project and creator.
If this key is not specified, the platform provides this metadata for the current creator and app.
For more information, see <<core-frontend-overview#_kojimetadata>>

== README.md

The `README.md` file is required at the top level your project directory.
This markdown file should document the tech stack and any relevant information to aid someone working with the code.
