= Anatomy of a Koji project
:page-slug: projects
:page-description: Description of the unique features and files in a Koji project that power the magic of customization.

A Koji project contains everything that defines a template, including the source code, build configurations, and unique configuration files that power Koji features.
When you fork a scaffold or another template to start your new template, the Koji platform creates a clone of the underlying project and opens it in the Koji editor.

As you add in the logic for your template, you must consider what additional features to offer, and then design experiences for different types of users and the different ways they might use it.
This page provides an overview of the functional considerations for a Koji template and a description of the required files and elements that power them.

//Koji provides you with an environment for developing and publishing an application in your browser.
//The project environment includes a terminal connected to a running container with all the familiar tools, the same code editor that powers VSCode, and tools to help you deploy and publish your application to https://withkoji.com[withkoji.com].

//== Koji template features and functions

== Source control

Koji projects use Git repositories for source control.
A project directory on the Koji CDN stores the underlying code base and configuration files for each template.
When you fork a scaffold or template, the underlying project directory is cloned, and your new project directory is associated with the following Git repositories.

* `origin` – The Git repository for your project.
Your template is built and deployed from this repository.
To work locally, you can clone this repository and push changes to it.
* `upstream` – The Git repository from which your project was forked.
To propose changes to the template you forked, you can create pull requests for this repository.

When you open your project in the Koji editor, the development environment includes the project directory at `/usr/src/app` and Git remotes for these repositories.
To see the remotes from the editor, you can open a terminal tab and run `git remote -v`.

[source,bash]
----
root@c8ce449b5538:/usr/src/app# git remote -v
origin  https://projects.koji-cdn.com/8a129043-4c22-4be7-875f-38b422008695.git (fetch)
origin  https://projects.koji-cdn.com/8a129043-4c22-4be7-875f-38b422008695.git (push)
upstream        https://projects.koji-cdn.com/e4d6b4bf-781a-4a49-9f0f-1d9cf3bbb7ff.git (fetch)
upstream        https://projects.koji-cdn.com/e4d6b4bf-781a-4a49-9f0f-1d9cf3bbb7ff.git (push)
----

== Project directory structure and contents

A typical Koji project contains the `.koji` directory, which includes the configuration and build files for your template, a directory for each service in the template, and a README file.
For example:

[source,console]
----
.koji
├── customization
│   ├── about_customization.md
│   ├── colors.json
│   ├── images.json
│   ├── settings.json
├── project
│   ├── about_project.md
│   ├── deploy.json
│   ├── develop.json
│   └── entitlements.json
frontend
├── common
├── package-lock.json
├── package.json
README.md
----

For your project to be built and deployed as a template on the Koji platform, the required files are `develop.json` and `deploy.json`, in the `.koji/project` directory, and `README.md`, at the top level.

Additional files are required to enable certain Koji features, if they are implemented in your template.
These requirements include the JSON files for supporting custom values, in the `.koji/customization` directory, and the `entitlements.json` file, in the `.koji/project` directory.

////
=== .koji directory

The `.koji` directory contains the configuration and script files, including project configuration for development and deploy and customizations for Visual Customization Controls (VCCs).

* `README.md`: Displays project information in the project overview.
* `develop.json`: Lets the Koji editor know how your project development works (project path, port, start command, and events).
* `deploy.json`: Lets deploy know where your project build works (build path, port, build commands).

////

=== develop.json

The `.koji/project/develop.json` file contains the development configuration for your project.
It specifies the project path, port, start command, and events for the services in your template.
For example:

[source,json]
----
include::../_includes/develop.json[tags=**,indent=0]
----

The file defines the following properties for each service:

* `path` – Indicates the source code directory for the service.
* `port` – Indicates the port on which the development server will run.
* `startCommand` – Works with the start script defined in the `package.json` file of the service.

=== deploy.json

`.koji/project/deploy.json` contains deployment configuration for your project.
It specifies the build path, port, and build commands for the services in your template.

[source,json]
----
include::../_includes/deploy.json[tags=**,indent=0]
----

In `deploy.json` make sure to check that:

* `output`: Indicates the directory where your files will be compiled after the `"commands"` list is done.

* `type`: Is either `static` if the service deploys a static bundle (HTML, CSS, JS), or `dynamic` if the service deploys a server.
* `commands`: Lists the steps to build your project.

The .json files in this directory each have a very specific schema that controls how the Koji editor deals with files.
develop.json deals with setting up your editor so you will have the best editing experience and deploy.json tells Koji how to turn your code into a live app.

=== .koji/customization

The JSON files in this directory define the names, types, configuration options, and default values for VCCs used in the template.
Every file created in this directory is displayed in the VCC Explorer section in the left navigation pane.

The following file would be saved as `example.json` and displayed in the left pane as *Example*:

[source,JSON]
----
{
  "example":  {
    "param":  "this is the value of the param"
  },
  "@@editor":  [
    {
      "key":  "example",
      "name":  "Example",
      "icon":  "😄",
      "source":  "example.json",
      "fields":  [
        {
          "key":  "param",
          "name":  "An Example Parameter",
          "type":  "text"
        }
      ]
    }
  ]
}
----

If you are using the <<withkoji-vcc-package#>> package, you can access this property with `instantRemixing.get(['example', 'param'])`.

=== README.md

The `README.md` file is required at the top level your project directory.
This markdown file should document the tech stack and any relevant information to aid someone working with the code.
