= Project structure and configuration
:page-slug: projects
:page-description: Description of the directory structure, files, and configuration data in a development project that power the features of a Koji app.
:includespath: ../_includes

A repository on Koji contains everything that defines your development project, including the source code, assets, and configuration data.
This topic describes a typical repository structure and defines the configuration data that is required to develop and deploy apps on Koji.

== Source control on Git

The Koji platform uses Git repositories for source control.
A directory on the Koji CDN stores the underlying files for each development project.
When you start a new project by forking a scaffold or another app, the Koji platform creates a clone of the underlying repository.
Your new project directory is associated with the following Git repositories.

* `origin` – Git repository for your new project.
Your app is built and deployed from this repository.
To work locally, you can clone the repository and push changes to it.
* `upstream` – Git repository from which your project was forked.
To propose changes to the app you forked, you can create pull requests for this repository.

If you open your project in the Koji code editor, the development environment includes the project directory at `/usr/src/app` and Git remotes for these repositories.
To see the remotes, you can open a terminal tab and run `git remote -v`.

[source,console]
----
root@c8ce449b5538:/usr/src/app# git remote -v
origin  https://projects.koji-cdn.com/8a129043-4c22-4be7-875f-38b422008695.git (fetch)
origin  https://projects.koji-cdn.com/8a129043-4c22-4be7-875f-38b422008695.git (push)
upstream        https://projects.koji-cdn.com/e4d6b4bf-781a-4a49-9f0f-1d9cf3bbb7ff.git (fetch)
upstream        https://projects.koji-cdn.com/e4d6b4bf-781a-4a49-9f0f-1d9cf3bbb7ff.git (push)
----

== Directory structure and contents

A typical Koji project contains the `koji.json` configuration file and a README file at the root of the project directory, along with a directory for each service in the app.

In the following example, the app has directories for its backend and frontend services.

[source,console]
----
backend
├── src
├── package-lock.json
├── package.json
frontend
├── src
├── package-lock.json
├── package.json
koji.json
README.md
----

== Configuration data in koji.json

The `koji.json` file defines the instructions for building your code and deploying your app on the Koji platform.
It also defines the settings that are required for certain platform features.
To implement these platform features in your app, you initialize the @withkoji/core package with the configuration data in the `koji.json` file.

=== develop

The `develop` key defines the configuration instructions for a development environment, such as the Koji code editor.

For each service in your app, specify the following properties:

* `path` – Source code directory for the service.
* `port` – Port on which the development server will run.
* `startCommand` – Script that initiates a development build.
Define the script in the `package.json` file of the service directory.

In the following example, the development configuration defines frontend and backend services.

[source,JSON]
----
include::{includespath}/koji.json[tag=develop,indent=0]
----

=== deploy

The `deploy` key defines the configuration instructions for a production deployment of your app.

For each service in your app, specify the following properties:

* `output` – Directory where your files will be compiled after the build commands are run.
* `type` – One of the following: `static` if the service deploys a static bundle (HTML, CSS, JS) or `dynamic` if the service deploys a server.
* `commands` – Steps to build your project.

In the following example, the deployment configuration defines a static frontend and a dynamic backend service.

[source,JSON]
----
include::{includespath}/koji.json[tag=deploy,indent=0]
----

=== entitlements

The `entitlements` key configures the Koji platform features that are implemented in your app.

In the following example, the app allows creators to configure it (`InstantRemixing`), hides the default platform navigation for this configuration (`InstantRemixingNativeNavigation`), defines custom sharing data (`CustomMetadata`), and enables a dedicated experience for the creator (`AdminContext`).

[source,JSON]
----
include::{includespath}/koji.json[tag=entitlements,indent=0]
----

=== remixData

If your app provides configuration options for creators, the `remixData` key defines the default values for those settings.
To manage remix data in your app, you use the <<core-frontend-remix#, Remix class>> in the @withkoji/core package.
To provide placeholder values when creators first open the settings, use the `@@initialTransform` key.

In the following example, the app has a default background color and title that creators can change.

[source,JSON]
----
include::{includespath}/koji.json[tag=remixData,indent=0]
----

=== @@initialTransform

If your app provides configuration options for creators, the `@@initialTransform` key defines the placeholder values that override the default values when a creator first opens these settings.
To open the settings in your app, you use the `.createRemix` method in the <<core-frontend-ui-navigate#createRemix, UI/Navigate class>>.
If a placeholder value is not specified, the default values in the `remixData` key are used.

In the following example, the app resets the title to a placeholder value when creators first configure it.

[source,JSON]
----
include::{includespath}/koji.json[tag=initialTransform,indent=0]
----

=== metadata

Optionally, the `metadata` key can be used to override the following properties.

include::{includespath}/interface-KojiConfig.adoc[tag=KojiMetadataProps]

If this key is not specified, the platform provides this metadata at runtime, which enables your app to use the creator's current username and profile picture without collecting or managing it as remix data.

== README.md

The `README.md` file is required at the top level your project directory.
This markdown file should document the tech stack and any relevant information to aid someone working with the code.
This file is particularly important when you are developing a scaffold or another app that other developers can fork to start their projects.
