= Working locally
:page-slug: work-locally
:page-description: How to set up a web server and launch your Koji template on your development machine, so that you can work on it locally. 

Although Koji provides a feature-rich online project editor, you might prefer to use your own suite of development tools in some cases.
In the first part of this tutorial, you learned how to use Git to clone a Koji project template to your development machine, so that you can work on it locally.
In this tutorial, you learn these key skills:

* How to install a Node.js web server environment on your development machine.
* How to launch both a frontend and a backend server so that you can work with all aspects of your template within your local area network.

This is the second part in a three-part tutorial.

. <<use-git#>>
. *Working locally* (this tutorial)
. <<publish-locally-developed#>>

== Prerequisites

* Use Git to clone your project locally.
See the first part of the tutorial.
* https://nodejs.org/en/download/[Install Node.js] and its associated Node Package Manager (NPM).
In this tutorial, you will set up a Node.js server on your development computer.
Koji uses Node.js and add-on packages to deliver your web application to your users' browsers.

== Installing the dependencies

In the previous tutorial, you used Git to clone all the project-specific files to your local drive.
However, the files that actually run the local server have not yet been installed.
Fortunately, four of the cloned files contain all the information about the servers and other dependencies that you will need to set up the server environment and launch the template locally.
These are the `package.json` and `package-lock.json` files in the `frontend` and `backend` directories.

Before you can test the template on your development machine, you must install two sets of Node modules, one set to run the frontend and another set to run the backend.

. Open a terminal window, and go to the `backend` directory.
. Run the following command.
+
[source,bash]
npm install
+
NPM reads the contents of the `package-lock.json` file and installs the listed files in a `node_modules` directory within the `backend` directory.
You'll have to wait for a few minutes while the terminal window shows you what's happening.
+
[source,bash]
----
~/Repos/Koji/MyKojiTemplate$ cd backend
~/Repos/Koji/MyKojiTemplate/backend$ npm install

> core-js@2.6.9 postinstall /home/kojicoder/Repos/Koji/MyKojiTemplate/backend/node_modules/core-js
> node scripts/postinstall || echo "ignore"

npm WARN koji-project-backend@1.0.0 No description
npm WARN koji-project-backend@1.0.0 No repository field.
... (more warnings and comments not shown) ...

added 477 packages from 234 contributors and audited 8550 packages in 6.678s
found 0 vulnerabilities
----
. Go to the `frontend` directory and run the following command.
+
[source,bash]
npm install
+
NPM installs the files listed in the `package-lock.json` file for the `frontend` service.
+
[source,bash]
----
~/Repos/Koji/MyKojiTemplate$ cd ../frontend/
~/Repos/Koji/MyKojiTemplate/frontend$ npm install

> koji-tools@0.5.3 postinstall /home/kojicoder/Repos/Koji/MyKojiTemplate/frontend/node_modules/koji-tools
> node ./cmd.js postinstall

new config

> preact@8.5.1 postinstall /home/kojicoder/Repos/Koji/MyKojiTemplate/frontend/node_modules/preact

> webpack-cli@3.3.1 postinstall /home/blackslate/Repos/Koji/MyKojiTemplate/frontend/node_modules/webpack-cli
> node ./bin/opencollective.js

npm WARN  meta-project@1.0.0 No repository field.
npm WARN meta-project@1.0.0 No license field.
... (more warnings and comments not shown) ...

added 996 packages from 358 contributors and audited 12188 packages in 14.023s
found 345 vulnerabilities (1 low, 344 high)
  run `npm audit fix` to fix them, or `npm audit` for details
----
. If you want to update all the Node modules to their most recent stable release, you can run the following command.
+
[source,bash]
npm audit fix
+
Your terminal will look something like this:
+
[source,bash]
----
~/Repos/Koji/MyKojiTemplate/frontend$ npm audit fix
npm WARN meta-project@1.0.0 No repository field.
npm WARN meta-project@1.0.0 No license field.
... (more warnings and comments not shown) ...

removed 2 packages and updated 4 packages in 7.468s
fixed 344 of 345 vulnerabilities in 12188 scanned packages
  1 vulnerability required manual review and could not be updated
----
NOTE: This process alters the `package-lock.json` file, so that it can request the identical file versions if you run `npm install` on a different computer.

== Launching your project locally

The https://withkoji.com/~Svarog1389/element-match[Element Match] game features both a frontend – so that you can play the game in your browser – and a backend – to access a database where the leaderboard scores are stored.

=== Launching projects without a backend

If you chose to develop a template that does not require a backend, such as a game without a leaderboard, launching your project locally is very simple.

. Go to the `frontend` directory and run the following command.
+
[source,bash]
npm start
+
Your terminal will look something like this:
+
[source,bash]
----
$ cd frontend/
$ npm install
$ npm start

... (some output not shown) ...
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
... (more output not shown) ...

ℹ ｢wds｣: Compiled successfully
----
. To see and test your project, go to `\http://0.0.0.0:8080` in your browser.
+
Alternatively, `\http://localhost:8080/` and `\http://127.0.0.1:8080/` might also work.

=== Launching projects with a backend

If you want to run a project with a backend, such as a leaderboard, the procedure for launching your template is more complex.
You must launch both the frontend and the backend servers on your local machine, using separate terminal windows for each.
To launch the frontend, you must specify the URL for connecting to the backend.
To launch the backend, you must provide deployment details for your project.
The Koji platform reads in these details from https://en.wikipedia.org/wiki/Environment_variable[environment variables] to ensure that the deployment data is kept separate from the code and configuration for your application.

==== Launching the frontend (Mac OS and other Unix-based operating systems)

By default, the frontend is configured to run at `\http://0.0.0.0:8080` and the backend is configured to run on port `3333`.
When you launch the frontend, you must specify the URL to use for accessing the backend.
On Mac OS and other Unix-based operating systems, you can use the `export` command to specify this URL.

. Open a terminal window, and go to the `frontend` directory.
. Run the following command, which sets the `KOJI_SERVICE_URL_backend` environment variable and then launches the frontend with `npm start`.
+
[source,bash]
----
export KOJI_SERVICE_URL_backend=http://0.0.0.0:3333 && npm start
----
+

+
Your terminal will look something like this:
+
[source,bash]
----
$ cd ..frontend/
$ export KOJI_SERVICE_URL_backend=http://0.0.0.0:3333 && npm start

... (some output not shown) ...
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
... (some output not shown) ...

ℹ ｢wds｣: Compiled successfully
----

==== Launching the frontend (Windows only)

By default, the frontend is configured to run at `\http://0.0.0.0:8080` and the backend is configured to run on port `3333`.
When you launch the frontend, you must specify the URL to use for accessing the backend.

1. Open a terminal window, and go to the `frontend` directory.
2. Run the following command to set the `KOJI_SERVICE_URL_backend` environment variable.
The command will differ slightly, depending on whether you are in a *Command prompt* or *Windows Powershell* terminal.

+
[.tabs]
--

.Command prompt
[source,bash]
----
set KOJI_SERVICE_URL_backend=http://localhost:3333
----

.Windows Powershell
[source,powershell]
----
$Env:KOJI_SERVICE_URL_backend=http://localhost:3333
----

--

+
{nbsp}

+
[IMPORTANT]
Keep this terminal window open and use it to run the other commands in this section.

+
Launching the frontend requires additional steps to start the file watcher alongside your project.
You must create a custom workflow to work locally that won't interfere with your project in the Koji editor.

3. Install npm-run-all.
+
[source,bash]
npm i --save-dev npm-run-all

4. Modify the `package.json` file.
+
[source,JSON]
{
  "scripts: {
    ...
    "watch": "koji-vcc watch",
    "start-windows": "npm-run-all -p watch start"
  }
}

5. Remove the `prestart` script in your `scripts` section, if there is one.

6. Launch the frontend with the following command.
+
[source,bash]
npm run start-windows

==== Launching the backend

The backend needs to have the values of the `KOJI_PROJECT_ID` and `KOJI_PROJECT_TOKEN` environment variables to access the leaderboard database.
You get the environment variables that Koji uses to deploy your project from the Koji editor.

. Open your project in the Koji editor.
. Open a new terminal tab and run the following command.
+
[source,bash]
env | grep 'KOJI_'
+
Your terminal will look something like this:
+
[source,bash]
----
root@ip-172-31-15-24:/usr/src/app# env | grep 'KOJI_'
...
KOJI_SERVICE_URL_backend=https://3333-48006672-6558-4f69-a40c-e4142c15067f.koji-staging.com

... (some variables not shown) ...

KOJI_PROJECT_ID=a70f8329-e89e-48b0-8d85-7658c1542b9f
KOJI_PROJECT_TOKEN=6679483a-dab8-4e89-9a83-6b56b53b4241
...
----
NOTE: This example was edited to show only the relevant items.
The values in your output will be unique to your project.

. Copy the output for the `KOJI_PROJECT_ID` and `KOJI_PROJECT_TOKEN`.
. On your local machine, create a file named `.env` at the root of your project, and paste the two lines that you have just copied into it.
+
Your file will look something like this (with your unique values):
+
[source,bash]
----
KOJI_PROJECT_ID=c00484db-827a-45bb-8541-f2c09c2f192e
KOJI_PROJECT_TOKEN=a6676f53-44fe-4109-819a-69df620ad7ed
----
. Open a new terminal window, and go to the backend directory of your project.
. Run the following command to launch the backend.
+
[source,bash]
npm run start-dev.
+
Your terminal will look something like this:
+
[source,bash]
----
$ cd ../backend/
$ npm run start-dev

> koji-project-backend@1.0.0 start-dev /home/kojicoder/Repos/Koji/MyKojiTemplate/backend
> NODE_ENV=development babel-watch -L --watch ../.koji/ src/server.js

[koji] backend started
----
+
Before `npm` starts the backend Node.js server, it reads the values in the `.env` file into the environment variables, so the backend server knows how to contact the Koji database.
+
NOTE: The Koji database is not running on your local machine, so you will still need an active Internet connection to get the leaderboard to work.
However, you will not need to make changes to the Koji database system, so you can focus on developing your template.

. If `npm` fails to read the values from the `.env` file, you can set the environment variables manually in the terminal before starting the server, using the `KOJI_PROJECT_ID` and `KOJI_PROJECT_TOKEN` values you copied earlier.
+
[.tabs]
--
.Linux
[source,bash]
----
export KOJI_PROJECT_ID=c00484db-827a-45bb-8541-f2c09c2f192e
export KOJI_PROJECT_TOKEN=a6676f53-44fe-4109-819a-69df620ad7ed
----

.Windows (command prompt)
[source,bash]
----
set KOJI_PROJECT_ID=c00484db-827a-45bb-8541-f2c09c2f192e
set KOJI_PROJECT_TOKEN=a6676f53-44fe-4109-819a-69df620ad7ed
----

.Windows (Powershell)
[source,powershell]
----
$Env:KOJI_PROJECT_ID=c00484db-827a-45bb-8541-f2c09c2f192e
$Env:KOJI_PROJECT_TOKEN=a6676f53-44fe-4109-819a-69df620ad7ed
----

--
+
{blank}
+
TIP: Another alternative is to use the https://www.npmjs.com/package/dotenv[dotenv] package to read the values from the `.env` file.

==== Starting the watcher on the backend (Windows only)


. Install npm-run-all.
+
[source,bash]
npm i --save-dev npm-run-all

. Modify the `package.json` file.
+
[source,JSON]
{
  "scripts: {
    ...
    "start-dev": "NODE_ENV=development babel-watch -L --watch ../.koji/ src/server.js",
    "start": "NODE_ENV=production node dist/server.js",
    "watch": "koji-vcc watch",
    "start-windows": "run-p watch start-dev"
  }
}

. Remove any duplicate scripts.

. Launch the backend with the following command.
+
[source,bash]
npm run start-windows

== Testing your local deployment

. In the terminal windows, check that the frontend reported `Compiled successfully` and the backend reported `backend started`.
. If you see errors, make sure that no other applications are running on ports `8080` and `3333`.
. In your browser, visit `\http://0.0.0.0:8080`.
+
You should see the Element Match game running.
. Click *Leaderboard* to check that it is working.
+
If you haven't played the game yet, there will be no scores to show, but you will see the Top Scores title and a Close link that returns you to the Welcome screen.
. Click *Start Matching*, and play the game.
. When the game is over, submit your user name.
+
The Leaderboard should now show your name and your score.

== Next steps

In this part of the tutorial, you learned how to:

. Install the Node modules that are needed to run a server on your local machine.
. Get the environment variables used by the server from the Koji editor.
. Create an `.env` file to apply these environment variables to the backend server, so that it can connect to the database.
. Tell the frontend which URL to use when connecting to the backend server.
. Launch the template locally.
. Check that the game and the leaderboard are working correctly.

You are now ready to start editing the template on your development machine and turning this project into your own template.
With what you have learned so far, you will be able to test all aspects of your template locally in your browser.

When you're ready to deploy your template for end users, you must publish it so they can access it from the Koji server.
To publish your template, you must update the repository that the Koji server uses to deliver your template.
For more information, see <<publish-locally-developed#>>.
