= Finishing up
:page-slug: game-finishing-up
:page-description: Publishing, sharing, and adding more features to a Falling Objects game.
:figure-caption!:

In the <<game-thumbnail-preview#, previous section>> of the remixable game tutorial, you customized the preview image for sharing on social media.
That's it, you just created a *fun and remixable Koji game*!

In this section, you’ll
// tag::description[]
publish your game and share it with your friends, so they can compete for the top leaderboard spot.
// end::description[]

By the end of this section, you should feel comfortable:

* Publishing and sharing your game.
* Continuing to work on your Koji project.

== Publishing and sharing your game

To make your game available to the world, all that's left to do is to publish it.
In the Koji editor, use the *Publish Now* menu.
When publishing is finished, get the link to the live game so you can share it with your friends.

Go ahead and post your new game everywhere.
Let the world know about it!

You can also post your new game to the https://discord.gg/kMkjJQ6Phb[Koji Discord server].
While you're at it, post any suggestions and thoughts on how you think we can make this tutorial even better!

== Adding new features

The project is now your playground!
You can modify features or add new ones, make improvements, or anything else you can imagine.

Here are some suggestions for features you can try adding:

* Add horizontal speed to collectibles.
* Add multiple collectible images.
For example, falling donuts and falling cupcakes.
* Flip the rules so that you have to avoid everything.
* Add more animations to collectibles.
* Have the player be able to move in all directions, not just horizontally.
* Add keyboard controls.
* Add projectiles so you can shoot the falling objects.
* Make an MMORPG out of this! [small]#(just kidding)#
