= Managing difficulty
:page-slug: game-tutorial-managing-difficulty
:page-description: Managing difficulty
:figure-caption!:

Our game is finally playable!
But it might be a little too repetitive and easy.
We want it to get progressively more difficult over time, so that our players have more incentive to compete on the leaderboard.

In this section, we will:

- Define values that can be changed to increase the game difficulty.

- Define a function that handles that change at a set interval.

Remember how we had a function that handled our spawn logic?
We'll do something similar this time.

== Defining starting values

Let's define some more settings in `frontend/src/Components/Game/preload.js`.

[source,javascript]
----
...
const initializeValues = () => {
    ...
    game.difficultyIncreasePeriod = 2;
    game.difficultyIncreaseTimer = 2;
    game.difficultyIncreaseAmount = 0.1;
    game.speedLimit = 12;
    game.speedIncrease = 0.1;
}
----

== Defining the function to handle difficulty

Now we can create our handler function in `frontend/src/Components/Game/draw.js`.

[source,javascript]
----
...
const draw = () => {
    ...
    manageDifficulty();
}

const manageDifficulty = () => {
    game.difficultyIncreaseTimer -= game.delta();

    if (game.difficultyIncreaseTimer <= 0) {
        increaseDifficulty();
        game.difficultyIncreaseTimer = game.difficultyIncreasePeriod;
    }
}

const increaseDifficulty = () => {
    if (game.spawnPeriodMin > game.spawnPeriodLimit) {
        game.spawnPeriodMin -= game.difficultyIncreaseAmount;
        game.spawnPeriodMax -= game.difficultyIncreaseAmount;
    }

    if (game.speedMax < game.speedLimit) {
        game.speedMax += game.speedIncrease;
        game.speedMin += game.speedIncrease;
    }
}
----

So, using our timer, we periodically increase the difficulty by changing some game values -- up to a point.
It's important to set a limit to prevent the game from eventually becoming totally unplayable, which most players don't really consider a fun experience.

Every time the difficulty increases, we:

* Slightly decrease the period between the spawning of Collectibles.

* Slightly increase the falling speed of Collectibles.

== Wrapping up

*Congratulations!* We've finished developing the main part of our game!

Of course, you can go back and modify things, or add new features.
Everything's a bonus from now on!

In the <<game-tutorial-remix#,next section>>, we'll take a look at the `Remix` menu and make our assets customizable.