= Managing difficulty
:page-slug: game-tutorial-managing-difficulty
:page-description: Managing difficulty
:figure-caption!:

At this stage, our game is finally playable!

But right now, it might be a little too repetitive and easy. We want to progressively more difficult as time passes, so our players have more incentive to compete on the leaderboard.

During this section, we will:

- Define values that can be changed to increase the game difficulty
- Define a function that handles that change at a set interval

Remember how we had a function that handled our spawn logic? We can do something similar this time.

== Defining starting values

Let's define some settings in `frontend/src/Components/Game/preload.js` first:

[source,javascript]
-------------------
...
const initializeValues = () => {
    ...
    game.difficultyIncreasePeriod = 2;
    game.difficultyIncreaseTimer = 2;
    game.difficultyIncreaseAmount = 0.1;
    game.speedLimit = 12;
    game.speedIncrease = 0.1;
}
-------------------

== Defining the function to handle difficulty

Then we can create our handler function in `frontend/src/Components/Game/draw.js`:

[source,javascript]
-------------------
...
const draw = () => {
    ...
    manageDifficulty();
}

const manageDifficulty = () => {
    game.difficultyIncreaseTimer -= game.delta();

    if (game.difficultyIncreaseTimer <= 0) {
        increaseDifficulty();
        game.difficultyIncreaseTimer = game.difficultyIncreasePeriod;
    }
}

const increaseDifficulty = () => {
    if (game.spawnPeriodMin > game.spawnPeriodLimit) {
        game.spawnPeriodMin -= game.difficultyIncreaseAmount;
        game.spawnPeriodMax -= game.difficultyIncreaseAmount;
    }

    if (game.speedMax < game.speedLimit) {
        game.speedMax += game.speedIncrease;
        game.speedMin += game.speedIncrease;
    }
}
-------------------

So, using our timer we periodically increase our difficulty by changing some game values, up to a point. It's important to set a limit to prevent the game getting totally unplayable after some time, which most players don't really consider a fun experience.

Every time the difficulty increases, we:

* Slightly decrease the period at which Collectibles spawn
* Slightly increase the falling speed of Collectibles

== Wrapping up

*Congratulations!*

We've actually finished developing the main part of our game!

Of course, you can go back and try modifying something, or adding a new feature. Everything's a bonus from now on!

In the <<game-tutorial-remix#,next section>>, we'll take a look at the `Remix` menu and allow our assets to be customizable when this game is remixed.