= Example: Add in-app purchases to a game
:page-slug: game-iap-intro
:page-description: Tutorial for adding in-app purchases to an existing Koji game.
:page-banner: {imagesDir}/game-iap-payment-menu-ui.png
:figure-caption!:

In this tutorial, you will add an In-Game Purchase feature to an existing game on Koji.

If you're new to Koji, here are some tutorials that you might want to check out before continuing.

* <<start-tutorial#>>
* <<game-intro#>>

== Objective

The starting point for this tutorial is the https://withkoji.com/apps/fe97e8a4-127d-4a65-8695-395ae60944e4[Tower Stack] game, which was built on top of the https://withkoji.com/apps/game-dev-scaffold-1a7af5ea[Game Dev Scaffold].

Tower Stack is a hyper-casual game where the goal is to stack blocks as high as you can without missing any.
Each new block swings from the top of the screen and tapping releases it.
If you successfully land it on top of a previous block, you get a point.
If you miss it, you lose a life.

In the original version, the game ends when the player runs out of lives.
In this tutorial, you will add a feature that lets players buy more lives, if they choose to.
The *best part* is that whoever customizes the game gets to choose how much the new lives will cost!

Here's an example of the game that you will build in this tutorial.
You can check out the finished game https://withkoji.com/~Svarog1389/2d69[here].

+++
<iframe src="https://withkoji.com/@RachelSienko06/kw83" width="400" height="600"> </iframe>
+++

== Sections

[.card]
[.cardht190]
.1. <<game-iap-setting-up-koji-json#>>
[.init-cap]
include::setting-up-koji-json.adoc[tag=description]

[.card]
[.cardht190]
.2. <<game-iap-payment-menu#>>
[.init-cap]
include::payment-menu.adoc[tag=description]

[.card]
[.cardht190]
.3. <<game-iap-start-purchase#>>
[.init-cap]
include::start-purchase.adoc[tag=description]

[.card]
[.cardht190]
.4. <<game-iap-updating-game#>>
[.init-cap]
include::updating-game.adoc[tag=description]

[.card]
[.cardht190]
.5. <<game-iap-customization#>>
[.init-cap]
include::game-iap-customization.adoc[tag=description]

[.clearfloat]
{blank}

== Getting help

include::../../_includes/tutorialHelpMarko.adoc[tag=all]
