= Glossary
:page-slug: glossary
:page-description: Definitions of Koji-related terms.

context::
A state or mode that provides specific functionality in a Koji app.
The default mode is the first screen displayed when the user starts the app.
To determine the current context of a running app, use the Koji.playerState.context property in the @withkoji/core package.
Learn more: <<contexts#_contexts_of_a_koji_app, intro to context>>

creator::
Someone who creates media and other assets on social media and posts Koji apps to their Koji Profile.

developer::
Someone who writes code to create Koji apps.

user::
Someone who interacts with a Koji app on a creator's Koji Profile.

owner::
Someone who owns a specific version of the app. The developer owns the original version of the app; the creator who customized the app owns that specific customized version.

entitlement::
Permissions that allow the Koji app to use certain platform features, such as enabling customization or defining product information for in-app purchases.
Learn more: <<entitlements#>>

in-app purchase (IAP)::
A financial transaction made within a Koji app.

Koji app::
A mini web application that can be embedded in a Koji Profile, shared on social media platforms, embedded in any website, or sent via chat messengers or email.
Learn more: <<introduction#>>

Koji App Store::
The Koji marketplace for apps. After you publish your app, you can create a listing for it in the Koji App Store to increase its exposure to Koji users.
Learn more: <<app-store#>>

Koji player::
The engine that runs Koji apps.

Koji Profile::
A social media creator's "link in bio" which consolidates the creator's online presence.
A creator's Koji Profile can include Koji apps that allow their fans to interact with the creator and that allow the creator to monetize their followers.

player chrome::
The set of Koji platform menus and navigation that are displayed with the Koji app.
This includes the user's profile picture, which displays the user menu when clicked.

project::
A collection of code and associated assets (such as images and sounds) that are compiled, processed, and packaged into a Koji app.
Learn more: <<projects#>>

repository::
A version-controlled storage for your project files. Koji repositories are based on Git and hosted in the cloud.

staging URL::
The URL of the temporary location of your compiled app.
This location is available only while the Koji code editor is open.
You can share this URL with people who collaborate with you in the development of the app.

production URL::
The permalink of your app.
This URL remains the same even after you republish your app with additional changes.
When you create a listing for your app in the App Store, use this URL.
