= Using custom domains
:page-slug: custom-domains
:page-description: How to configure your Koji to use a custom domain.

The domain name for your Koji is its web address.
A domain name consists of a *root domain*, such as `+++withkoji.com+++`, and usually one or more subdomains.
For example, in the domain name `+++withkoji.com/~johnsmith789/my-video-game+++`, `+++~johnsmith789+++` and `+++my-video-game+++` are subdomains.
The Koji platform assigns a domain name to your Koji when you publish it.

You might want to assign a custom domain name to your Koji.
A custom domain name can be much easier to remember, and it usually just looks better.
Custom domains are about where you want to serve the experience.

Koji has several root domains that you can use at no cost and with no additional configuration, including:

* withkoji.com
* koji.sh
* koji.game

You can create a custom domain by adding a subdomain of your choosing in front of a Koji root domain.
For example, if you add "myvideogame" in front of ".koji.game", your custom domain name will be `+++myvideogame.koji.game+++`.

You can also use a domain name that you purchase from somewhere like *Google Domains* or *Namecheap*.
Then you can make your domain name almost anything you want it to be.
For example: `+++thenextgreatvideogame.com+++`.

[NOTE]
You can assign only one Koji subdomain to a Koji.
If you've already assigned a subdomain and you want to change it, follow the steps for <<_releasing_a_domain, releasing a domain>>.
Then you can assign the new one.
You can assign as many domains as you want to a Koji if they are domains you own.

== Using a subdomain with a Koji root domain

. Open the Koji and click the *Koji* button.
. Go to *Settings > Custom domains*.
. Click *New*.
. Select *Subdomain*.
. Click *Next*.
. Select a *root domain*.
. Enter the name that you want to come before the subdomain.
. Click *Save*.
If the domain name you chose is already taken, "That domain is not available" will be displayed.
If the domain name is available, the complete domain name will be displayed.
. Click the domain name.
You should see a message verifying that your custom domain has been successfully assigned to the Koji.
. Click *Open* to go to the new URL.
Your Koji should be displayed.

== Using a domain you own

 . Use your domain provider's management tools to configure the appropriate DNS records.
+
[NOTE]
If you want to host your Koji on a subdomain of your custom domain name (for example, *www.mycustomdomain.com or game.mycustomdomain.com*), you need to use your domain provider's tools to add a CNAME record for that subdomain (*www* or *game*) that points to *cnames.withkoji.com*.

. Open the Koji and click the Koji button.
. Go to *Settings > Custom domains*.
. Click *New*.
. Select *A domain you own*.
. Click *Next*.
. Enter your complete domain name.
. Click *Save*.
The domain name should be displayed.
. Click the domain name.
You should see a message verifying that your custom domain has been successfully assigned to the Koji.
. Click *Open* to go to the new URL.
Your Koji should be displayed.

== Releasing a domain

. Open the Koji and click the Koji button.
. Go to *Settings > Custom domains*.
. Click the domain name you want to release.
. Click *Release domain*.
. Click *Yes, release*.