= Enabling plugins in your Koji template
:page-slug: plugins
:page-description: Plugins

A plugin is a piece of software that can be added to any Koji to provide additional functionality.
Basically, it allows for the injection of dynamic code. A plugin is added to a Koji after publication, so it is not specific to a particular Koji.
For example, the *Custom Boilerplate* plugin adds a popup requiring users to agree to boilerplate before interacting with the Koji.

== Advantages of plugins

In addition to allowing the developer to easily add functionality to a Koji, plugins offer a few other advantages.

. Search engines and social crawlers often do not render JavaScript when indexing pages.
For instance, if you're using React, a bot may only see the root div and an "enable JavaScript" message.
A plugin can overcome this limitation by injecting keywords into a webpage's header.
Because Koji plugins are computed server-side, they are available to all bots without any additional 
configuration or 3rd-party services.

. A plugin can inject a new file at runtime, simplifying the creation of things like web app manifests.
The developer just provides configurable values for the plugin and the injection intelligently wraps them with the code/syntax that makes sense.

== Limitations

. Koji plugins are not designed to modify app functionality or to inject code that interfaces with an app's native code.
This is an intentional decision to avoid fragmentation and "spaghetti" code.
Meaningful changes to functionality should be done within the code of the template, and repeated core behaviors should leveage JavaScript packages and the larger JavaScript community.

. Plugins are only injected into static services.

. If your app contains multiple static services, plugins will be injected into all of them.
There is no way to enable or disable plugins on a per-service basis.




