= Supporting rich previews
:page-slug: rich-preview-image
:page-description: How to customize the rich preview (Open Graph) image for your Koji template.
:page-banner: {imagesDir}/Koji-screenshot=1.png

When a user shares a remix of your template on social media, the Koji platform renders a rich preview (Open Graph) image based on a screenshot of the Koji.
By default, the platform takes a screenshot of the initial view.

In some cases, the initial view might not be the best preview image for your template.
For example, if a game template starts with an instruction screen, a screenshot of the first level might provide a better preview image.
To improve the sharing experience in these cases, you can render a custom view of your template that is designed specifically to make an impression when sharing a remix.

You can also control the timing of the screenshot to ensure that all relevant assets have loaded before the preview image is generated.

== Customizing the sharing image

To customize the sharing image for your template, render a custom view when the URL contains the `koji-screenshot=1` query parameter.
For optimal rich preview support, design this view with the following considerations in mind.

* Responsiveness.
* Looks good with a square aspect ratio.
* Includes customizable elements to generate unique previews of each remix.

image::Koji-screenshot=1.svg[Render a view for the rich preview image]

For the following example, assume the template supports remixes of the title, font size, and logo.

include::../_includes/starterExamples.adoc[tag=all]

. In your application code, add a conditional statement to display a different image for social shares.
For example:
+
[.tabs,scope="lang"]
--
.React
====
[.intro]
Add a conditional statement in the `render` function.

[source,JavaScript]
----
render() {
  if (window.location.search.includes('koji-screenshot=1')) {
    return (
      <SocialSharePreview>
          <H1
          fontSize={this.state.titleOptions.fontSize}
          >{this.state.titleOptions.title}</H1>
          <Image src={this.optimizeURL(this.state.logo)} />
        </SocialSharePreview>
    );
  }
  ...
}
----
====

.Vanilla JS
====
[.intro]
Wrap a conditional statement around the `render` function.

[source,JavaScript]
----
// render the social share preview
const socialShareRender = () => {
    document.body.innerHTML = `
        <div id="socialSharePreview">
            <h1 style="font-size:${titleSize}px" id="title">${title}</h1>
            <img id="logo" src="${optimizeURL(logo)}"/>
        </div>`;
}

// render
if (window.location.search.includes('koji-screenshot=1')) {
    socialShareRender();
} else {
    render();
}
----
====

.Angular
====
[.intro]
Add a conditional statement in the `ngOnInit` function and use it to apply a dynamic `id`.

[.tabs]
=====
.app.component.ts
[source,JavaScript]
----
ngOnInit() {
  ...
  this.social = false
  if (window.location.search.includes('koji-screenshot=1')) {
    this.social = true
  }
  ...
}
----

.app.component.html
[source,JavaScript]
----
<div class="container" id="{{social ? socialSharePreview : ''}}">
        <h1 style="fontSize: {{titleOptions.fontSize}}px;">{{titleOptions.title}}</h1>
        <img src="{{optimizeURL(logo)}}"
    />
    </div>
----
=====
====

.Svelte
====
[.intro]
Add a conditional statement in the `App.svelte` file.

[source,JavaScript]
----
{#if (window.location.search.includes('koji-screenshot=1'))}
    <div class="social-share" style="background-image: url('{optimizeURL(image)}');">
    <h1 style='font-size: {titleOptions.fontSize}px'>{titleOptions.title}</h1>
    </div>
{:else}
...
{/if}
----
====

--
. Define appropriate styles for the rich preview image.
+
To ensure that it is displayed correctly, design the rich preview image as a responsive square.
+
[.tabs,scope="lang"]
--
.React
[source,JavaScript]
----
const SocialSharePreview = styled.div`
  background-color: #395b88;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  text-align: center;
  color: #fcfcfc;
`;
----

.Vanilla JS
[source,CSS]
----
#socialSharePreview {
  background-color: #395b88;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  text-align: center;
  color: #fcfcfc;
}
----

.Angular
[source,CSS]
----
#socialSharePreview {
  background-color: #395b88;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  text-align: center;
  color: #fcfcfc;
}
----

.Svelte
[source,CSS]
----
.social-share {
  background-color: #395b88;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  text-align: center;
  color: #fcfcfc;
}
----

--
. To test the preview image, open your staging link and append `?koji-screenshot=1` to the URL.

== Controlling the screenshot timing

The Koji platform uses the `window.kojiScreenshotReady` property to determine the timing of the rich preview screenshot.

When the platform loads a template, it checks for `window.kojiScreenshotReady = false;`.
If this value isn't present, the platform takes the screenshot right away.
If it is, the platform sets an interval to check the value every 100ms.
When the value changes to `true` or a maximum interval of 2000ms elapses, the platform takes the screenshot.

This feature enables you to ensure that the relevant fonts, images, videos, and other assets have loaded before the sharing image is generated.
For example:

. In the `index.html` file, add the following script tag.
+
[source, HTML]
<script> window.kojiScreenshotReady = false; </script>

. In your application code, add the following code after confirming that the relevant assets have loaded.
[source, JavaScript]
window.kojiScreenshotReady = true;
