= @withkoji/dispatch
:page-slug: withkoji-dispatch-package

The @withkoji/dispatch package enables you to
//tag::description[]
implement real-time functionality in your Koji template.
//end::description[]
For example, chats, multi-player games, and polls.

This reference provides examples for common methods.
For more information, see the https://github.com/madewithkoji/koji-dispatch[package documentation on GitHub].

== Install

Install the package in your Koji project.

NOTE: You must also install the <<withkoji-vcc-package#>> package.

[source,bash]
npm i --save @withkoji/dispatch

== Dispatch

[.hcode, id="new Dispatch", reftext="new Dispatch"]
=== new Dispatch(project)

Instantiates `Dispatch`.

==== Parameters

* `project` – Object containing the details of your Koji project.
** `projectId` – String, unique identifier for your Koji project.
You can use the <<withkoji-vcc-package#>> package to obtain this value programmatically.
** `options` – (Optional) Object containing the configuration options for dispatch shards.
*** `shardName` – (Optional) String, name of the specific shard to use.
If this key is not present, the user will be placed into a shard automatically.
*** `maxConnectionsPerShard`– (Optional) Number of users to allow on a shard before it is "full."
When a shard is full, new users are added to a new shard unless a different shard is explicity set.

==== Example

[source,javascript]
----
import Dispatch from '@withkoji/dispatch';
const dispatch = new Dispatch({
  projectId: instantRemixing.get(['metadata', 'projectId']),
  options: {
    shardName: 'explicitShardName',
    maxConnectionsPerShard: 20,
  }
});
----

[.hcode, id=".clientId", reftext="clientId"]
=== .clientId

_String_, ID of the currently connected client.

[.hcode, id=".connectedClients", reftext="connectedClients"]
=== .connectedClients

_Object_ containing IDs of currently connected clients as keys and an object containing their user data.

==== Example
[source,json]
----
{
	"0dc15e36-81b4-442b-be4d-bf590ee73c2a": {
		username: "test1",
		lastPing: 1600218622595
	},
	"1fe2eb80-57e3-435f-9314-faa74853c34a": {
		username: "test2",
		lastPing: 1600218623097
	}
}
----

[.hcode, id=".latency", reftext="latency"]
=== .latency

_Number_, the latency of the last message in milliseconds.

[.hcode, id=".shardName", reftext="shardName"]
=== .shardName

_String_, name of the shard the client is currently connected to.

[.hcode, id=".userInfo", reftext="userInfo"]
=== .userInfo

_Object_, the user info of the currently connected client.

[.hcode, id=".connect()", reftext="connect()"]
=== .connect()

(Async) Connects the dispatch client to an open shard.

==== Example

[source,javascript]
dispatch.connect();

[.hcode, id=".disconnect()", reftext="disconnect()"]
=== .disconnect()

(Async) Disconnects the dispatch client from the active connection. 

==== Example

[source,javascript]
dispatch.disconnect();

[.hcode, id=".emitEvent()", reftext="emitEvent()"]
=== .emitEvent(eventName, payload)

Emits the named event to all clients on the current shard.

==== Parameters

* `eventName` – _String_, name of the event.
* `payload` – _Any_, data to send with event.

==== Example

[source,javascript]
dispatch.emitEvent('myEvent', myDataPayload);

[.hcode, id=".info()", reftext="info()"]
=== .info()

Gets info on the shard the client is currently connected to.

==== Returns

(Async) _ShardInfo_, Object describing the shard the client is currently connected to with shard name and number of connected clients.

==== Example

[source,javascript]
----
dispatch.info.then((info) => {
    currentInfo = info;
});
----

[.hcode, id=".on()", reftext="on()"]
=== .on(eventName, callback)

Sets a callback to listen to a specific event and run when the event is dispatched over the shard.

TIP: For Koji custom events see <<#_dispatch_event, DISPATCH_EVENT>>.

==== Parameters

* `eventName` – _String_, name of the event to subscribe to.
* `callback` – _Callback_, the callback to run when the event is fired.

==== Example

[source,javascript]
dispatch.on('myEvent', myCallbackFunction);

[.hcode, id=".removeEventListener()", reftext="removeEventListener()"]
=== .removeEventListener(eventName)

Removes listeners from the specified event.

==== Parameters

* `eventName` – _String_, name of the event to remove listeners from.

==== Example

[source,javascript]
dispatch.remveEventListener('myEvent');

[.hcode, id=".setUserInfo()", reftext="setUserInfo()"]
=== .setUserInfo(userInfo)

Sets the current client's user info for the currently connected shard.

==== Parameters

* `userInfo` – _Any_, the data for user info to set.

==== Example

[source,javascript]
dispatch.setUserInfo({username:"myUsername"});

== DISPATCH_EVENT

Constant holding special event keys for Koji Dispatch.
To subscribe to these events see <<#.on()>>.

[.hcode, id="CONNECTED", reftext="CONNECTED"]
=== CONNECTED

The event fired when the current client has successfully connected to a shard.

==== Example

[source,javascript]
----
import Dispatch, { DISPATCH_EVENT } from '@withkoji/dispatch';

const dispatch = new Dispatch({
  projectId: instantRemixing.get(['metadata', 'projectId'])
});

dispatch.connect();

dispatch.on(DISPATCH_EVENT.CONNECTED, ({ clientId, shardName }) => {
	// client has connected to shard
});
----


[.hcode, id="CONNECTED_CLIENTS_CHANGED", reftext="CONNECTED_CLIENTS_CHANGED"]
=== CONNECTED_CLIENTS_CHANGED

The event fired when the list of clients currently connected to the shard changes.

==== Example

[source,javascript]
----
import Dispatch, { DISPATCH_EVENT } from '@withkoji/dispatch';

const dispatch = new Dispatch({
  projectId: instantRemixing.get(['metadata', 'projectId'])
});

dispatch.connect();

dispatch.on(DISPATCH_EVENT.CONNECTED_CLIENTS_CHANGED, ({ connectedClients }) => {
	// connected clients has changed
});
----

== Utils

Koji dispatch includes utility functions to help you build realtime multiplayer games and applications.

[source,javascript]
import { Utils } from '@withkoji/dispatch';

[.hcode, id=".profanity()", reftext="profanity()"]
=== .profanity(string)

Checks whether a string contains profanity.
This method can be useful for checking usernames or chat content.

==== Parameters

* `string` – String to check.

==== Returns

Boolean that indicates whether the specified string contains profanity.

==== Example

[source,javascript]
Utils.profanity('check this string');

[.hcode, id=".filterProfanity()", reftext="filterProfanity()"]
=== .filterProfanity(string)

Replaces profanity in a string with asterisks.

==== Parameters

* `string` – String to sanitize.

==== Returns

String, replaces profanity in the specified string with asterisks.

==== Example

[source,javascript]
Utils.filterProfanity('sanitize this string');

== Related resources

* https://github.com/madewithkoji/koji-dispatch[@withkoji/dispatch on Github]
* <<vote-counter-blueprint#>>