= @withkoji/iap (deprecated)
:page-slug: withkoji-koji-iap-package
:page-description: Package for implementing in-app purchases from your Koji templates.

include::../../docs/_includes/deprecatedPackage.adoc[tag=all]

The @withkoji/iap package enables you to
//tag::description[]
implement in-app purchases from your Koji templates.
//end::description[]
For example, require a purchase to unlock a premium asset or a game.
This package provides frontend methods, for managing transactions with users, and backend methods, for validating purchases against receipts.

To implement a basic purchase flow in your template, use `getToken` on the frontend to obtain the current user's token. Then, use the callback function to route a request to the backend.
On the backend, use `resolveReceipts` to determine whether the user has purchased the product and return appropriate information to the frontend.
Finally, on the frontend, display the appropriate experience based on whether or not the product has been purchased.
For example, display a premium image that has been purchased.
Or, if the user hasn't purchased the image, display a *Purchase* button and use `startPurchase` to initiate a transaction when the user clicks the button.

== Install

Install the package in the frontend and backend services of your Koji project.

[source,bash]
----
npm install --save @withkoji/iap
----

IMPORTANT: To support instant remixes of your template, you must also install the <<withkoji-vcc-package#>> package and implement the `VccMiddleware` on your backend server.
This middleware maintains the environment variables for instant remixes, ensuring that purchases are applied to the correct remix version.

== Iap

To enable in-app purchases for your Koji template, you must implement the `Iap` class and define the `InAppPurchases` object in the `.koji/project/entitlements.json` file.

.Entitlements
[source,json]
----
{
  "entitlements": {
    "InAppPurchases": {
      "enabled": true,
      "products": [
        0 : {
          "sku": "productID", <1>
          "name": "{{scope.nameKey}}", <2>
          "price": "{{scope.priceKey}}", <3>
          "quantity": "{{scope.quantity}}",<4>
          "fulfillment": "email", <5>
          "isConsumable": true, <6>
          "dynamicReceipt":true <7>
        }
      ]
    }
  }
}
----
<1> `sku` – Identifier for the product to purchase.
<2> `name` – Description displayed when a user is prompted to purchase the product.
Can be a string or a path to the <<vcc-overview#,Visual Customization Control (VCC)>> that defines the description.
<3> `price` – Path to the VCC that defines the purchase price, if applicable.
Alternatively, use `"priceIsUnset": true` to define a product without a set price.
For example, a donation or "pay what you want" price.
<4> `quantity` – (Optional) Maximum number of times the product can be sold.
After the inventory threshold is reached, further purchase attempts will display a “sold out!” message.
If quantity is not present or is `0`, the product will never sell out.
<5> `fulfillment` – User information to collect for order fulfillment.
Possible values are `email`, `phone`, or `address`.
This value is stored as a custom attribute on the <<_iapreceipt,transaction receipt>>.
<6> `isConsumable` – (Optional) Whether the product can be purchased more than once.
<7> `dynamicReceipt` – (Optional) Whether the transaction receipt can display routes in the Koji.
If enabled, a query parameter is appended to the URL when the buyer or seller views the receipt.
For example, `dynamic-receipt=buyer` or `dynamic-receipt=seller`.

[.hcode, id="new Iap", reftext="new Iap"]
=== new Iap(projectID, projectToken)

Instantiates `Iap`.

==== Parameters

* `projectID` – (Backend only) _String_, unique identifier for the Koji.
* `projectToken` – (Backend only) _String_, secret key for the Koji.

TIP: When instantiating `Iap` on the backend, you must provide these parameters, which are available as environment variables at runtime.
For instant remixes, you must implement `VccMiddleware` to manage these variables.
See <<withkoji-vcc-package#>>.

==== Example

[source,javascript]
----
import Iap from '@withkoji/iap';

// Frontend
const iap = new Iap();

// Backend
const iap = new Iap(
  res.locals.KOJI_PROJECT_ID,
  res.locals.KOJI_PROJECT_TOKEN,
);
----

== Iap methods

[.hcode, id=".getToken", reftext="getToken"]
=== .getToken(handler, forceRefresh)

Gets a token identifying the current user, and invokes a callback function to handle backend requests for the user's purchases.

==== Parameters

* `handler` – _Function_, handles backend requests for the user's purchases.
Receives the following property as input:
** `userToken` – _String_, temporary token for the current user's session.
+
[NOTE]
include::../../docs/_includes/userTokenNote.adoc[tags=all;!auth-only]
To resolve purchases for a given user, both the user token, obtained on the frontend, and the project token, obtained from environment variables on the backend, are necessary.

* `forceRefresh` – (Optional) _Boolean_, indicates whether to generate a new user token before invoking the callback function (`false` by default).

==== Example

[source,javascript]
----
iap.getToken((token) => {
  // Request user's purchases and update template based on what has or has not been purchased
});
----

[.hcode, id=".loadProduct", reftext="loadProduct"]
=== .loadProduct(sku)

Gets the properties for a specified product to enable the template to leverage dynamic product information.
For example, you can check the stock for a product with limited quantity (via the `numAvailable` property), and indicate the number of remaining items.

==== Parameters

* `sku` – _String_, identifier for the product.

==== Returns

(Async) <<_iapproduct>> object, properties of the specified product.

==== Example

[source,javascript]
----
const product = await iap.loadProduct(sku);
----

[.hcode, id=".resolveReceipts", reftext="resolveReceipts"]
=== .resolveReceipts(userToken)

Retrieves the user's receipts, which can be used to validate purchases for specific products.

==== Parameters

* `userToken` – _String_, temporary token for the current user's session.
See <<.getToken>>.

==== Returns

(Async) Array of <<_iapreceipt>> objects, the user's purchases.

==== Example

[source,javascript]
----
const receipts = await iap.resolveReceipts(token);
// Look for the SKU to determine whether the user has purchased the product
hasPurchased = !!(receipts.find(({ product }) => product.sku === 'productID'));
----

[.hcode, id=".resolveReceiptById", reftext="resolveReceiptById"]
=== .resolveReceiptById(receiptId)

Retrieves a specific transaction receipt, which can be used to facilitate fulfillment.
For example, use a dynamic receipt to upload a video response from the seller and then share that response with the buyer.

==== Parameters

* `receiptId` – _String_, unique identifier for the receipt.

==== Returns

(Async) <<_iapreceipt>> object for the specified receipt.

==== Example

[source,javascript]
----
const receipt = await iap.resolveReceiptById(token);
// Use custom attributes for a video response
this.setState({
  instructions: receipt.attributes.message,
  video: receipt.attributes.video,
});
----

[.hcode, id=".resolveReceiptsBySku", reftext="resolveReceiptsBySku"]
=== .resolveReceiptsBySku(sku)

Retrieves all receipts for a specified product, which can be used to aggregate sales data.

==== Parameters

* `sku` – _String_, identifier for the product.
Products are defined in the <<#_iap,entitlements file>> and registered or updated when the project is deployed.

==== Returns

(Async) Array of <<_iapreceipt>> objects for the specified product.

==== Example

[source,javascript]
----
const receipts = await iap.resolveReceiptsBySku(sku);
----

[.hcode, id=".startPurchase", reftext="startPurchase"]
=== .startPurchase(sku, handler, purchaseOptions)

Prompts the user to purchase a product, and invokes a callback function to handle the results of the purchase.

==== Parameters

* `sku` – _String_, identifier for the product to purchase.
Products are defined in the <<#_iap,entitlements file>> and registered or updated when the project is deployed.
* `handler` – _Function_, handles the results of the purchase.
Receives the following properties as input:
** `success` – _Boolean_, indicates whether the purchase was successful.
** `userToken` – _String_, temporary token for the current user's session.
See <<.getToken>>.
** `receiptId` – _String_, unique identifier for the receipt, if the purchase was successful, or `undefined`, if not.
* `purchaseOptions`– _Object_, custom information to add to the transaction receipt.
Contains the following properties:
** `amount` – _Number_, (Optional) amount of the purchase.
** `customMessage` – _String_, (Optional) custom message associated with the purchase.
This value is stored as a custom attribute on the <<_iapreceipt,transaction receipt>>.

==== Example

[source,javascript]
----
iap.startPurchase(sku, (success, token, purchaseOptions) => {
  // Update template based on whether the purchase was successful
});
----

[.hcode, id=".updateReceipt", reftext="updateReceipt"]
=== .updateReceipt(receiptId, attributes, notificationMessage)

Updates the custom attributes for a specified receipt.
For example, if a user purchases a "power up" and then uses it in a game, you can update the receipt to indicate that the product has been consumed and is not available for future sessions.

==== Parameters

* `receiptId` – _String_, unique identifier for the receipt.
* `attributes` – _Object_, list of key-value pairs to update.
* `notificationMessage` – _String_, (Optional) custom message to sent the user when the receipt is updated (up to 80 characters).
If undefined, the message will read: `Your receipt for PRODUCT_NAME was updated`.

==== Returns

(Async) _Any_, confirmation of the update, if the request was successful, or an error message, if not.

==== Example

[source,javascript]
----
const receipt = await iap.updateReceipt(receiptId, { isConsumed: true }, 'Your power up has been used');
----

== Iap objects

=== IapReceipt

An `IapReceipt` object represents a receipt for a user's purchase of a product.
To determine whether a user has purchased a specific product, you can use <<.resolveReceipts>> to retrieve the `IapReceipt` objects associated with the user's token, and then look for a receipt with the product's SKU.

The `IapReceipt` object includes the following properties.

TIP: Be sure to implement appropriate error handling to account for differences in object structure or empty values.

[source,javascript]
----
{
  id: string; <1>
  userId: string; <2>
  productId: string; <3>
  purchasedPrice: number; <4>
  attributes: { [index: string]: any }; <5>
  datePurchased: Date; <6>
  product?: IapProduct; <7>
  transaction?: Transaction|null; <8>
  transactionIds: { <9>
    credit: string;
    debit: string;
  };
}
----
<1> `id` – Unique identifier for the receipt.
<2> `userId` – Koji user name of the user who purchased the product.
The `userId` return value will always be `unavailable`.
To avoid leaking/fingerprinting users at a global level, Kojis must interact with users via a short-lived user token.
See <<.getToken>>.
<3> `productId` – Unique identifier for the product.
<4> `purchasedPrice` – Price the user paid for the product.
<5> `attributes` – Object containing a list of custom key-value pairs associated with the receipt.
You can use <<.updateReceipt>> to update these values.
Additionally, the fulfillment information (`email`, `phone`, or `address`) and `customMessage` are included this object, if set at purchase time.
<6> `datePurchased` – Date of the purchase.
<7> `product` – <<_iapproduct>> object that represents the purchased product.
<8> `transaction` – Object that represents the transaction information, if available.
<9> `transactionIds` – Object containing references to the associated transaction receipts – `credit` for the user receiving the funds (seller), `debit` for the user sending the funds (buyer).
To link to the transaction receipt in the user's Koji wallet, use the format `\https://withkoji.com/payments/transactions/TXN_ID`.

=== IapProduct

An `IapProduct` object represents a specific product for purchase.
Products are defined in the <<#_iap,entitlements file>> and registered or updated when the project is deployed.
You can use <<.loadProduct>> to retrieve the properties associated with the product's SKU.

The `IapProduct` object includes the following properties.

[source,javascript]
----
{
  id: string; <1>
  appId: string; <2>
  ownerUserId: string; <3>
  price: number; <4>
  priceIsUnset: boolean; <5>
  isConsumable: boolean; <6>
  name: string; <7>
  sku: string; <8>
  dateCreated: Date; <9>
  isActive: boolean; <10>
  fulfillment?: 'email'|'phone'|'address'; <11>
  quantity?: number; <12>
  numAvailable?: number; <13>
  owner?: UserArtifact; <14>
  purchases?: IapReceipt[]; <15>
}
----
<1> `id` – Unique identifier for this version of the product.
<2> `appId` – Name of the Koji from which the product was purchased.
<3> `ownerUserId` – Koji user name of the creator.
<4> `price` – Purchase price of the product.
Defined in the  <<#_iap,entitlements file>> of the template.
<5> `priceIsUnset` – Indicator of whether a purchase price is defined for the product.
Defined in the entitlements file of the template.
<6> `isConsumable` – Indicator of whether a product can be purchased more than once.
Defined in the entitlements file of the template.
<7> `name` – Description displayed when the user was prompted to purchase the product.
Defined in the entitlements file of the template.
<8> `sku` – Identifier of the purchased product.
Defined in the entitlements file of the template.
<9> `dateCreated` – Date the product was registered or updated, which happens when the project is deployed.
<10> `isActive` – Indicator of whether the product is still available for purchase.
<11> `fulfillment` – Type of user information collected for order fulfillment.
Defined in the entitlements file of the template.
<12> `quantity` – Total number of times the product can be sold (inventory threshold).
Defined in the entitlements file of the template.
<13> `numAvailable` – Remaining number of times the product can be sold.
Calculated based on the total inventory defined in the entitlements file, less the number of purchases.
<14> `owner` – Object that represents the template publisher ("seller").
<15> `purchases` – Array of <<_iapreceipt>> objects representing purchases of the product.

== Related resources

* https://github.com/madewithkoji/koji-iap[@withkoji/iap on Github]
* https://withkoji.com/code/sean/aoyl[Reference project]
