= @withkoji/koji-iap
:page-slug: withkoji-koji-iap-package
:page-description: Enable in-app purchases from your Koji templates.

The @withkoji/koji-iap package enables you to
//tag::description[]
implement in-app purchases from your Koji templates.
//end::description[]
For example, require a purchase to unlock a premium asset or a game.
This package provides frontend methods, for managing transactions with users, and backend methods, for validating purchases against receipts.

To implement a basic purchase flow in your template, use `getToken` on the frontend to obtain the current user's token. Then, use the callback function to route a request to the backend.
On the backend, use `resolveReceipts` to determine whether the user has purchased the product and return appropriate information to the frontend.
Finally, on the frontend, display the appropriate experience based on whether or not the product has been purchased.
For example, display a premium image that has been purchased.
Or, if the user hasn't purchased the image, display a *Purchase* button and use `promptPurchase` to initiate a transaction when the user clicks the button.

== Install

Install the package in the frontend and backend services of your Koji project.

IMPORTANT: To support instant remixes of your template, you must also install the <<withkoji-vcc-package#>> package and implement the `VccMiddleware` on your backend server.
This middleware maintains the process variables for instant remixes, ensuring that purchases are applied to the correct remix version.

[source,bash]
----
npm install --save @withkoji/iap
----

== Iap

To enable in-app purchases for your Koji template, you must implement the `Iap` class and define the `InAppPurchases` object in the `.koji/project/entitlements.json` file.

.Entitlements
[source,json]
----
{
  "entitlements": {
    "InAppPurchases": {
      "enabled": true,
      "products": [
        0 : {
          "sku": "productID", <1>
          "name": "Purchase prompt", <2>
          "price": "{{scope.key}}" <3>
        }
      ]
    }
  }
}
----
<1> Identifier for the product to purchase.
<2> Description displayed when a user is prompted to purchase the product.
<3> Path to the <<vcc-overview#,Visual Customization Control (VCC)>> that defines the purchase price.

[.hcode, id="new Iap", reftext="new Iap"]
=== new Iap(projectID, projectToken)

Instantiates `Iap`.

==== Parameters

* `projectID` – (Backend only) String, unique identifier for your Koji project.
* `projectToken` – (Backend only) String, unique token for your Koji project.

TIP: When instantiating `Iap` on the backend, you must provide these parameters, which Koji maintains as environment variables.
For instant remixes, you must implement `VccMiddleware` to manage these variables.
See <<withkoji-vcc-package#>>.

==== Example

[source,javascript]
----
import Iap from '@withkoji/iap';

// Frontend
const iap = new Iap();

// Backend
const iap = new Iap(
  process.env.KOJI_PROJECT_ID,
  process.env.KOJI_PROJECT_TOKEN,
);
----

[.hcode, id=".getToken", reftext="getToken"]
=== .getToken(handler[userToken], forceRefresh)

Gets a token identifying the current user, and invokes a callback function to handle backend requests for the user's purchases.

==== Parameters

* `handler` – Function to handle backend requests for the user's purchases.
* `userToken` – String, unique identifier for the current user.
* `forceRefresh` – (Optional) Boolean that indicates whether to force a refresh before invoking the callback function (`false` by default).

==== Example

[source,javascript]
----
iap.getToken((token) => {
  // Request user's purchases and update template based on what has or has not been purchased
});
----

[.hcode, id=".promptPurchase", reftext="promptPurchase"]
=== .promptPurchase(sku, handler[success, userToken])

Prompts the user to purchase a product, and invokes a callback function to handle the results of the purchase.

==== Parameters

* `sku` – String, identifier for the product to purchase.
Products are defined in the <<#_iap,entitlements file>> and registered or updated when the template is published.
* `success` – Boolean that indicates whether the purchase was successful.
* `handler` – Function to handle the results of the purchase.
* `userToken` – String, unique identifier for the current user.

==== Example

[source,javascript]
----
iap.promptPurchase(sku, (success, token) => {
  // Update template based on whether the purchase was successful
});
----

[.hcode, id=".resolveReceipts", reftext="resolveReceipts"]
=== .resolveReceipts(userToken)

Retrieves the user's receipts, which can be used to validate purchases for specific products.

==== Parameters

* `userToken` – String, unique identifier for the current user.

==== Returns

(Async) Array of <<#_iapreceipt>> objects for the user's purchases.

==== Example

[source,javascript]
----
const receipts = await iap.resolveReceipts(token);
// Look for the SKU to determine whether the user has purchased the product
hasPurchased = !!(receipts.find(({ product }) => product.sku === 'productID'));
----

[.hcode, id=".updateReceipt", reftext="updateReceipt"]
=== .updateReceipt(receiptId, attributes)

Updates the custom attributes for a specified receipt.

==== Parameters

* `receiptId` – String, unique identifier for the receipt.
* `attributes` – Object containing a list of attribute values to update.

==== Returns

(Async) Confirmation of the update, if the request was successful, or an error message, if not.

==== Example

[source,javascript]
----
const today = new Date();
const receipt = await iap.updateReceipt(receiptId, { lastAccessed: today });
----

== IapReceipt

An `IapReceipt` object represents a receipt for a user's purchase of a product.
To determine whether a user has purchased a specific product, you can use use <<#.resolveReceipts>> to retrieve the `IapReceipt` objects associated with the user's token, and then look for a receipt with the product's SKU.

The `IapReceipt` object includes the following properties.

TIP: Be sure to implement appropriate error handling to account for differences in object structure or empty values.

[source,javascript]
----
{
    attributes: { [index: string]: any }; <1>
    datePurchased: string; <2>
    id: string; <3>
    product: {
      appId: string; <4>
      dateCreated: string; <5>
      id: string; <6>
      isActive: boolean; <7>
      name: string; <8>
      ownerUserId: string; <9>
      price: number; <10>
      sku: string; <11>
    };
    productId: string; <12>
    userId: string; <13>
  }
----
<1> Array of custom attributes associated with the receipt.
You can use <<#.updateReceipt>> to update these values.
<2> Date of the purchase.
<3> Unique identifier for the receipt.
<4> Name of the Koji template from which the product was purchased.
<5> Date the product was registered or updated, which happens when the template is published.
<6> Unique identifier for this version of the product.
<7> Indicator of whether the product is still available for purchase.
<8> Description displayed when the user was prompted to purchase the product.
Defined in the <<#_iap,entitlements file>> of the template.
<9> Koji user name of the template owner.
<10> Price the user paid for the product.
Defined in the entitlements file of the template.
<11> Identifier of the purchased product.
Defined in the entitlements file of the template.
<12> Unique identifier for the product.
<13> Koji user name of the user who purchased the product.

== Related resources

* https://github.com/madewithkoji/koji-iap[@withkoji/koji-iap on Github]
* https://withkoji.com/templates/sean/aoyl/code[Reference project]
