= @withkoji/custom-vcc-sdk
:page-slug: withkoji-custom-vcc-sdk

The @withkoji/custom-vcc-sdk package enables you to
//tag::description[]
implement custom Visual Customization Controls (VCCs) for your template.
//end::description[]

== Install

Install the package in your Koji project.

[source,bash]
npm install --save @withkoji/custom-vcc-sdk

== CustomVcc

[.hcode, id="new CustomVcc", reftext="new CustomVcc"]
=== new CustomVcc()

Instantiates `CustomVcc`.

==== Example

[source,javascript]
----
import { CustomVcc } from '@withkoji/custom-vcc-sdk';
const customVcc = new CustomVcc();
----

== CustomVcc methods

[.hcode, id=".blur", reftext="blur"]
=== .blur()

Tracks blur events on the custom VCC for live collaboration.

==== Example

[source,javascript]
----
customVcc.blur();
----

[.hcode, id=".change", reftext="change"]
=== .change(newValue)

Updates the VCC value with the user-entered value.

==== Parameters

* `newValue` – _Any_, current value of the VCC.

==== Example

[source,javascript]
----
customVcc.change(newValue);
----

[.hcode, id=".focus", reftext="focus"]
=== .focus()

Tracks focus events on the custom VCC for live collaboration.

==== Example

[source,javascript]
----
customVcc.focus();
----

[.hcode, id=".onTheme", reftext="onTheme"]
=== .onTheme(handler)

Listens to changes to the theme value, to retrieve values relating to the Koji display theme.

==== Parameters

* `handler` – _Function_, called when theme is available, first parameter will be the theme object.

==== Example

[source,javascript]
----
customVcc.onTheme((theme) => {
	// theme is a Koji editor theme of the shape: { colors: {}, mixins: {} }
 	// save this value in order to style your VCC to match the user's current theme
});
----

[.hcode, id=".onUpdate", reftext="onUpdate"]
=== .onUpdate(handler)

Listens to changes in the custom value from the consumer application to enable updates to rendered values.

TIP: It is prefereable to update the rendered value only in response to `onUpdate` events.
Calling `change` immediately fires an `onUpdate`.

==== Parameters

* `handler` – _Function_, handle changes to the custom value.

==== Example

[source,javascript]
----
customVcc.onUpdate((props) => {
	// props is an object containing the VCC's current state. it looks like:
	const {
		type, // the type signature for this vcc
		name, // string name of the VCC
		value, // current value of the VCC
		scope, // name of the section where this vcc appears
		variableName, // resolved variable name of this vcc (`scope.key`)
		options, // an object containing any options passed in `typeOptions`
		collaborationDecoration, // an object containing any collaborators currently focused on this control
		_config, // the full VCC configuration file. Generally this is not needed, as most controls should be fully isolated to a single value, but this can be useful when creating more complex custom controls like map builders
	} = props;
});
----

[.hcode, id=".register", reftext="register"]
=== .register(width, height)

Indicates that the custom VCC has loaded and registers it to trigger the on events from the parent editor.

==== Parameters

* `width` – (Optional) _Any_, width of the custom VCC.
* `height` – (Optional) _Any_, height of the custom VCC.

==== Example

[source,javascript]
----
customVcc.register('300', '300');
----

[.hcode, id=".save", reftext="save"]
=== .save()

Saves the JSON customization file in the consumer application.

==== Example

[source,javascript]
----
customVcc.save();
----

[.hcode, id=".showModal", reftext="showModal"]
=== .showModal(type, currentValue, onComplete)

Triggers the `image`, `sound`, `file`, and `obj` (3D) modals using the SDK and specifies callbacks when those modals have been resolved.

==== Parameters

* `type` – _String_, modal type to display, possible values are `image`, `sound`, `obj` and `file`.
* `currentValue` – _Any_, current value of the custom VCC.
* `onComplete` – _Function_, called when modal has been resolved.

==== Example

[source,javascript]
----
customVcc.showModal('image', myImageUrl, (newUrl) => {
  // change and save VCC to use the new URL value
});
----

[.hcode, id=".uploadFile", reftext="uploadFile"]
=== .uploadFile(file, fileName, onComplete)

Uploads a file blob to the Koji CDN.

==== Parameters

* `file` – _Blob_, file blob data to be uploaded.
* `fileName` – _String_, name of the file to be uploaded.
* `onComplete` – _Function_, called when upload has completed.

==== Example

[source,javascript]
----
customVcc.uploadFile(myBlob, myFileName, (url) => {
  // url of the uploaded file
});
----

== Related resources

* https://github.com/madewithkoji/koji-custom-vcc-sdk[@withkoji/custom-vcc-sdk on Github]
* <<build-custom-vcc#>>
* <<cat-selector-blueprint#, Blueprint: Custom VCC>>
