= @withkoji/vcc
:page-slug: withkoji-vcc-package
:page-description: Implement core platform features in your Koji template, including instant remixing, Visual Customization Controls (VCCs), and the Koji feed.

The @withkoji/vcc package enables you to
//tag::description[]
implement core platform features in your Koji template, including instant remixing, Visual Customization Controls (VCCs), and the Koji feed.
//end::description[]

* Dynamically get and set custom values in Koji customization files.
* Expose VCCs so that a user can change the customizable elements in your template.
* Monitor changes to custom values with a watcher function.
* Ensure the template is displayed correctly in the Koji feed.
* Monitor and handle state transitions between in and out of focus in the Koji feed.

== Install

Install the package in your Koji project.

[source,bash]
npm install --save @withkoji/vcc

== Start the watcher

Reconfigure the `package.json` file to run the watcher (`koji-vcc watch`) concurrently with your development server.
You can use a package like npm-run-all.
For example:

include::../../docs/_includes/startWatcherPackageJSONReact.adoc[tags=*]

== InstantRemixing

Instant remixing enables users to customize values directly from the template preview, rather than from the Koji editor, for a quick and easy way to remix without coding.

IMPORTANT: To empower casual users, implementing instant remixes for your templates is strongly recommended.

To enable instant remixing for your Koji template, you must implement the `InstantRemixing` class and enable the `InstantRemixing` entitlement in the `.koji/project/entitlements.json` file.

.Entitlements
[source,json]
----
{
  "entitlements": {
    "InstantRemixing": true
  }
}
----

[.hcode, id="new InstantRemixing", reftext="new InstantRemixing"]
=== new InstantRemixing()

Instantiates `InstantRemixing`.

==== Example

[source,javascript]
----
import { InstantRemixing } from '@withkoji/vcc';
const instantRemixing = new InstantRemixing();
----

== InstantRemixing Methods

[.hcode, id=".get", reftext="get"]
=== .get(path)

Gets initial values from Koji customization files or either of the special predefined environment values: `metadata` or `serviceMap`.

* `metadata` – project data, contains `projectId`, the unique identifier for the Koji project.
* `serviceMap` – endpoints for your currently registered services.

==== Parameters

* `path` – Array of _Strings_, keys pointing to the desired VCC value.

==== Returns

_Any_, value of the <<vcc-overview#_vcc_types,VCC type>> at the specified path.

==== Example

[source,javascript]
----
const myVariable = instantRemixing.get(['scope', 'key']);
const projectId = instantRemixing.get(['metadata', 'projectId']);
const backendService = instantRemixing.get(['serviceMap', 'backend']);
----

[.hcode, id=".onPresentControl", reftext="onPresentControl"]
=== .onPresentControl(path, position)

Opens a VCC to enable editing of a custom value.
For example, show the title VCC when a user taps an editable title.

==== Parameters

* `path` – Array of _Strings_, keys pointing to the VCC value.
* `position` – (Optional) _Object_, the size and position of the affected element, to keep it in the frame during editing.

==== Example

[source,javascript]
----
instantRemixing.onPresentControl(['scope', 'key']);

// With optional position object
const {
  x,
  y,
  width,
  height,
} = e.target.getBoundingClientRect();
this.instantRemixing.onPresentControl(['result', 'position'], {
  position: { x, y, width, height },
});
----

[.hcode, id=".onSetActivePath", reftext="onSetActivePath"]
=== .onSetActivePath(handler)

Listens to the path of the currently active VCC control to enable a different experience when editing values (for example, highlight the active control or pause the interface).

==== Parameters

* `handler` – _Function_, handles changes to the current control.
Receives the following property as input:
** `path` – Array of _Strings_, the path of the active VCC control.

==== Example

[source,javascript]
----
instantRemixing.onSetActivePath((path) => {
  // Change control experience
});
----

[.hcode, id=".onSetCurrentState", reftext="onSetCurrentState"]
=== .onSetCurrentState(handler)

Listens to the changes to the current state.
If a template has more than one state, the available states are listed when remixing so the user can switch between them.

States are optional and, if used, must be defined in the `.koji/customization/quickstart.json` file.

[source,json]
----
{
   "quickstart": {
        "states": [
            { "key": "choice", "label": "Choice scene" },
            { "key": "result", "label": "Result scene" }
        ]
    }
}
----

==== Parameters

* `handler` – _Function_, handles changes to the current state.
Receives the following property as input:
** `state` – _String_, key of the active state.

==== Example

[source,javascript]
----
instantRemixing.onSetCurrentState((state) => {
  // Change experience per state
});
----

[.hcode, id=".onSetRemixing", reftext="onSetRemixing"]
=== .onSetRemixing(handler)

Listens to changes in remix state to enable different template experiences during remix than during preview or use.

==== Parameters

* `handler` – _Function_, handles changes in remix state.
Receives the following properties as inputs:
** `isRemixing` – _Boolean_, indicates whether this app is in remixing mode.
** `editorAttributes` – _Object_, describes the current editor.

==== Example

[source,javascript]
----
instantRemixing.onSetRemixing((isRemixing, editorAttributes) => {
  // Change template experience
  // editorAttributes.type will be set to either "full" or "instant"
});
----

[.hcode, id=".onSetValue", reftext="onSetValue"]
=== .onSetValue(path, newValue, skipUpdate)

Explicitly sets the value for the VCC at the specified path.

==== Parameters

* `path` – Array of _Strings_, keys that points to the desired VCC value.
* `newValue` – _Any_, New value for the <<vcc-overview#_vcc_types,VCC type>> at the specified path.
* `skipUpdate` – (Optional) _Boolean_, indicates whether to skip the `onValueChanged` callback for this update (`false`, by default).
To allow the template to manage the update state, set this parameter to `true`.
+
TIP: The `skipUpdate` option is useful for preventing unnecessary round trip notifications in some cases.
For example, during text inputs.

==== Example

[source,javascript]
----
instantRemixing.onSetValue(['scope', 'key'], newValue, skipUpdate);
----

[.hcode, id=".onValueChanged", reftext="onValueChanged"]
=== .onValueChanged(handler)

Listens to changes in custom values.

==== Parameters

* `handler` – _Function_, handles changes to custom values.
Receives the following properties as inputs:
** `path` – Array of _Strings_, the path of the changed VCC control.
** `newValue` – _Any_, the new value of the changed VCC control.

==== Example

[source,javascript]
----
instantRemixing.onValueChanged((path, newValue) => {
  // Use new custom value in template
});
----

[.hcode, id=".ready", reftext="ready"]
=== .ready()

Indicates that the application is ready to start receiving events.

==== Example

[source,javascript]
instantRemixing.ready();

== VccMiddleware

This package includes an http://expressjs.com/en/guide/using-middleware.html[Express middleware] for access to VCC values from dynamic backends, as a companion to the frontend `InstantRemixing` class.

To implement this middleware, add it to your express server.

[source,javascript]
----
import { VccMiddleware } from '@withkoji/vcc';

const app = express();
app.use(VccMiddleware.express);
----

To access application-specific VCC values from an express endpoint, use `res.locals.koji` and the `scope` and `key` of the vcc value you require.

[source,javascript]
----
app.get('/test', (req, res) => {
  // res.locals.koji.scope.key
});
----

== FeedSdk

The Koji feed enables users to browse available templates, moving them from off screen or out of focus, into the main window of the feed.

To ensure a template is displayed correctly in the Koji feed, you must implement the `FeedSdk` and enable the `FeedEvents` entitlement in the `.koji/project/entitlements.json` file.

.Entitlements
[source,json]
----
{
  "entitlements": {
    "FeedEvents": true
  }
}
----

[.hcode, id="new FeedSdk", reftext="new FeedSdk"]
=== new FeedSdk()

Instantiates `FeedSdk`.

==== Example

[source,javascript]
----
import { FeedSdk } from '@withkoji/vcc';
const feed = new FeedSdk();
----

== FeedSdk Methods

[.hcode, id=".load", reftext="load"]
=== .load()

Indicates the template is ready to display and registers touch event handlers to bubble up touch events to the feed controller (if your template needs to own a gesture, see <<#.requestCancelTouch>>).

IMPORTANT: You must call this method when the template has loaded.
Otherwise, the feed will display a loading state, and will eventually time out and move to the next template in the feed.

==== Example

[source,javascript]
feed.load();

[.hcode, id=".onPlaybackStateChanged", reftext="onPlaybackStateChanged"]
=== .onPlaybackStateChanged(handler[isPlaying])

Monitors visibility in the Koji feed, enabling the template to play certain features when it is in focus and pause them when it isn't in focus.
For example, play or pause audio, video, a timer, or a countdown.

TIP: To test autoplaying features, you can open a published template and append `?feedDebug=true` to the URL.
The template is loaded in the feed 10 times, and you can swipe or scroll through to ensure the features start and stop as expected.

==== Parameters

* `handler` – Function to handle changes to template visibility in the feed.
* `isPlaying` – Boolean that indicates whether the template is in focus in the feed.

==== Example

[source,javascript]
----
feed.onPlaybackStateChanged((isPlaying) => {
  // Handle autoplay features
});
----

[.hcode, id=".requestCancelTouch", reftext="requestCancelTouch"]
=== .requestCancelTouch()

Cancels touch event handlers for the feed so that the template can use the gesture.
If your template uses gestures, you can use this method at any time during the touch lifecycle to take control of the action.

TIP: Because a feed is composed of iframes, the parent feed control can't capture touch events due to security policies.
Therefore, the `load` method bubbles up touch events to the Koji feed controller so that users can browse templates in the feed.
If your template also uses touch controls, you can use the `requestCancelTouch` method to ensure the template actions take precedence over the feed actions for those controls.

==== Example

[source,html]
----
<div ontouchmove={(e) => feed.requestCancelTouch()}>
  no touch control
</div>
----

== Keystore

The `Keystore` module is used in conjunction with the <<secret#, secret VCC type>>.
The secret VCC allows setting of sensitive data such as product keys in a VCC without the value being visible when projects get remixed.
Keystore is used to access the value in the secret VCC within your application code.

NOTE: For security purposes `Keystore` is only available in backened services and cannot be used in user facing services.

=== new Keystore

Instantiates Keystore.

==== Parameters
* `projectId` – (Optional) _String_, the ID of the Koji project to attach the keystore to.
Defaults to the current projects ID.
* `projectToken` – (Optional) _String_, the token of the Koji project to attach the keystore to.
Defaults to the current projects token.

==== Example

[source,javascript]
----
import { Keystore } from '@withkoji/vcc';
const keystore = new Keystore();
----

== Keystore methods

[.hcode, id=".resolveValue", reftext="resolveValue"]
=== .resolveValue(keyPath)

Description

==== Parameters

* `keyPath` – _String_, the path for accessing the key.
This is acquired from the VCC value of the secret type VCC.

==== Returns

_String_, raw value of the secret VCC.

==== Example

[source,javascript]
const password = await keystore.resolveValue(res.locals.koji.api.key);


== Related resources

* https://github.com/madewithkoji/koji-vcc[@withkoji/vcc on Github]
