= @withkoji/custom-vcc-sdk
:page-slug: withkoji-custom-vcc-sdk

The @withkoji/custom-vcc-sdk package enables you to
//tag::description[]
implement custom Visual Customization Controls (VCCs) for your template.
//end::description[]

The Koji platform includes VCCs for standard elements, such as images, text, and sounds. In addition, you can build custom VCCs to provide new types of customizations that match closely with the application you are developing. For example, some Koji templates provide tile map editors, sound enhancers, or custom avatar creators to enhance the interactivity for remixers.

== Install

Install the package in your Koji project.

[source,bash]
npm install --save @withkoji/custom-vcc-sdk

== CustomVcc

[.hcode, id="new CustomVcc", reftext="new CustomVcc"]
=== new CustomVcc()

Instantiates `CustomVcc`.

==== Example

[source,javascript]
----
import CustomVcc from '@withkoji/custom-vcc-sdk';
const customVcc = new CustomVcc();
----

== CustomVcc methods

[.hcode, id=".change", reftext="change"]
=== .change(newValue)

Updates the VCC value with the user-entered value.

==== Parameters

* `newValue` – _Any_, current value of the VCC.

==== Example

[source,javascript]
----
customVcc.change(newValue);
----

[.hcode, id=".onTheme", reftext="onTheme"]
=== .onTheme(handler)

Listens to changes to the theme value, to retrieve values relating to the Koji display theme.
The theme returned in the listener allows you to style the VCC to match the user’s current theme on Koji (dark or light).

==== Parameters

* `handler` – _Function_, called when theme is available.
Receives the following property as input:
** `theme` – _Object_, represents the theme as an object, see <<Theme>>

==== Example

[source,javascript]
----
customVcc.onTheme((theme) => {
	// theme is a Koji editor theme
 	// save this value in order to style your VCC to match the user's current theme
});
----

[.hcode, id=".onUpdate", reftext="onUpdate"]
=== .onUpdate(handler)

Listens to changes in the custom value from the consumer application to enable updates to rendered values.

TIP: It is prefereable to update the rendered value only in response to `onUpdate` events.
Calling `change` immediately fires an `onUpdate`.

==== Parameters

* `handler` – _Function_, handle changes to the custom value.
Receives the following property as input:
** `props` – _Object_, contains the properties of the VCC, see <<Props>>.

==== Example

[source,javascript]
----
customVcc.onUpdate((props) => {
	// props is an object containing the VCC's current state.
});
----

[.hcode, id=".register", reftext="register"]
=== .register(width, height)

Indicates that the custom VCC has loaded and registers it to trigger the on events from the parent editor.

==== Parameters

* `width` – (Optional) _Any_, width of the custom VCC.
* `height` – (Optional) _Any_, height of the custom VCC.

==== Example

[source,javascript]
----
customVcc.register('300', '300');
----

[.hcode, id=".save", reftext="save"]
=== .save()

Saves the JSON customization file in the consumer application.

==== Example

[source,javascript]
----
customVcc.save();
----

[.hcode, id=".showModal", reftext="showModal"]
=== .showModal(type, currentValue, onComplete)

Opens the specified modal type, and invokes a callback function when the user selects a value in the modal.
The available modal types correspond to the built-in VCCs of the same name.
When a value is chosen in the modal it invokes the onComplete handler passing the new value to it.

==== Parameters

* `type` – _String_, modal type to display. Possible values are `image`, `sound`, `obj`, and `file`.
* `currentValue` – _Any_, current value of the custom VCC.
* `onComplete` – _Function_, called when modal has been resolved.
Receives the following property as input:
** `newValue` – _Any_, the value set within the modal by the user.

==== Example

[source,javascript]
----
customVcc.showModal('image', myImageUrl, (newUrl) => {
  // change and save VCC to use the new URL value
});
----

[.hcode, id=".uploadFile", reftext="uploadFile"]
=== .uploadFile(file, fileName, onComplete)

Uploads a file blob to the Koji CDN.

==== Parameters

* `file` – _Blob_, file blob data to be uploaded.
* `fileName` – _String_, name of the file to be uploaded.
* `onComplete` – _Function_, called when upload has completed.
Receives the following property as input:
** `url`  – _String_, URL of the uploaded file.

==== Example

[source,javascript]
----
customVcc.uploadFile(myBlob, myFileName, (url) => {
  // url of the uploaded file
});
----

== CustomVcc objects

=== Props

A `props` object respresents the properties representing the current state of a custom VCC.
It is returned to the handler listening to <<onUpdate>>.

The `props` object includes the following properties.

[source,javascript]
----
{
	type: string;<1>
	name: string;<2>
	value: any;<3>
	scope: string;<4>
	variableName: string;<5>
	options: object;<6>
	collaborationDecoration: object;<7>
	_config: object;<8>
};
----
<1> `type` – the type signature for this vcc.
<2> `name` – string name of the VCC.
<3> `value` – current value of the VCC.
<4> `scope` – name of the section where this vcc appears.
<5> `variableName` – resolved variable name of this vcc (`scope.key`).
<6> `options` – an object containing any options passed in `typeOptions`.
<7> `collaborationDecoration` – an object containing any collaborators currently focused on this control.
<8> `_config` – the full VCC configuration file. Generally this is not needed, as most controls should be fully isolated to a single value, but this can be useful when creating more complex custom controls like map builders.

=== Theme

A `theme` object allows you to style using matching colours and styles from remixers' active theme.
It is returned to the handler listening to <<onTheme>>.

The `theme` object includes the following properties.

[source,javascript]
----
{
	name: string;<1>
	breakpoints: object;<2>
	colors: object;<3>
	mixins: object;<4>
};
----
<1> `name` – name of the theme.
<2> `breakpoints` – an object contain responsive style breakpoints of the theme.
<3> `colors` – an object of key-value pairs representing the theme's named colors.
<4> `mixins` – an object containing css mixins to style specific elements.

== Related resources

* https://github.com/madewithkoji/koji-custom-vcc-sdk[@withkoji/custom-vcc-sdk on Github]
* <<build-custom-vcc#>>
* <<cat-selector-blueprint#, Blueprint: Custom VCC>>
