= @withkoji/user-defaults
:page-slug: withkoji-user-defaults-package

The @withkoji/user-defaults package provides
//tag::description[]
a secure interface for accessing permissioned user data across all Koji templates.
//end::description[]

A template can request data with a reserved key, for the user's Koji profile data, or with a user key that is defined in any template on Koji, for additional preferences.
This data can then be used to autofill values and personalize experiences.
For example, automatically enter the user's name in a leaderboard, or display the user’s avatar in a game.

Keys defined in any template are available in a global, unscoped namespace and do not need to be registered.
When a value is requested that is not a reserved key, Koji checks whether the user has entered a value for it, either on the current template or on a different template.
If not, the user is prompted to submit a value and allow it to be saved for later reuse.
This method enables users to own and manage their data in a transparent, portable way, rather than relying on cookies or other measures.

== Install

Install the package in your Koji project.

[source,bash]
----
npm install --save @withkoji/user-defaults
----

== KojiUserDefaults

[.hcode, id="new KojiUserDefaults", reftext="new KojiUserDefaults"]
=== new KojiUserDefaults()

Instantiates `KojiUserDefaults`.

==== Example

[source,javascript]
----
import KojiUserDefaults from '@withkoji/user-defaults';
const kojiUserDefaults = new KojiUserDefaults();
----

[.hcode, id=".onConnect", reftext="onConnect"]
=== .onConnect(handler[isConnected])

Listens to the connection state to enable access to permissioned user data.

==== Parameters

* `handler` – Function to handle requests for user data.
* `isConnected` – Boolean that indicates whether the data bridge is connected.

==== Example

[source,javascript]
----
kojiUserDefaults.onConnect((isConnected) => {
  // If connected, get user name
  if (isConnected) {
    kojiUserDefaults.get('profile.username', (success, key, value) => {
      console.log(success, key, value);
    });
  }
});
----

[.hcode, id=".get", reftext="get"]
=== .get(key, handler[success, key, value])

Gets a specified piece of user data and invokes a callback function to handle the results of the request.

==== Parameters

* `key` – String, key of the user data to retrieve. See <<_keys>>.
* `handler` – Function to handle the results of the data request.
* `success` – Boolean that indicates whether the request was successful.
* `value` – String, value of the user data, if the request was successful. For an unsuccessful request, the value is `undefined`.

==== Example

[source,javascript]
----
kojiUserDefaults.get('profile.username', (success, key, value) => {
  console.log(success, key, value);
});
----

[.hcode, id=".promptLogin", reftext="promptLogin"]
=== .promptLogin()

Prompts the user to log in to Koji.

==== Example

[source,javascript]
----
kojiUserDefaults.promptLogin();
----

== Keys

The following *reserved keys* can be used to access data from the user's Koji profile.

* `profile.username`
* `profile.profilePicture`
* `profile.reputation`

User keys defined in any other template represent string values in an unscoped, portable, global storage.
For example, you could define a key in your template called `user.favoriteColor`, and then reuse that value in any other Koji template.

== Related resources

* https://github.com/madewithkoji/koji-user-defaults-sdk[@withkoji/user-defaults on Github]
