= @withkoji/database
:page-slug: withkoji-database-package
:page-description: Package for implementing a Koji database for the backend of your template.

Each Koji project includes a key-value store that you can use as a backend database for simple use cases, such as collecting information from users, aggregating survey or poll results, and creating leaderboards for games.
Koji databases are made up of one or more `collections`.
Each `collection` stores a series of database entries with a unique key and collection of key-value pairs.
Values within the key-value pairs can be of any type, including strings, numbers, and arrays.

The @withkoji/database package enables you to
//tag::description[]
implement a Koji database for the backend of your template.
//end::description[]
In `immediate` mode (default), you send database updates one request at a time.
In `transaction` mode, you can batch several updates together by calling `beginTransaction`, calling the request methods, and then calling `commitTransaction` to submit the batch.

== Install

Install the package in the backend service of your Koji project.

[WARNING]
====
* To maintain adequate read/write security, your template must connect to the database only from a backend route.
* To support instant remixes of your template, you must also install the <<withkoji-vcc-package#>> package and implement the `VccMiddleware` on your backend server.
This middleware maintains the environment variables for instant remixes, ensuring that database access is restricted to the correct remix version.
====

[source,bash]
----
cd backend
npm install --save @withkoji/database
----

== Database

[.hcode, id="new Database", reftext="new Database"]
=== new Database(config, mode)

Instantiates `Database`.

==== Parameters

* `config` – (Required for instant remix support) _Object_, environment variables that serve as access credentials.
Contains the following properties:
** `projectID` – _String_, unique identifier for the Koji.
** `projectToken` – _String_, secret key for the Koji.

+
TIP: For templates that support instant remixes, you must implement `VccMiddleware` to manage these variables.
See <<withkoji-vcc-package#>>.

* `mode` – (Optional) _String_, when to send updates to the database.
Use one of the following modes:
** `immediate` – send one update at a time (default).
** `transaction` – send one or more updates in a batch.
See <<.beginTransaction>> and <<.commitTransaction>>.

==== Example

[source,javascript]
----
import Database from '@withkoji/Database';
const database = new Database({
  projectId: res.locals.KOJI_PROJECT_ID,
  projectToken: res.locals.KOJI_PROJECT_TOKEN,
});
----

== Database methods

[.hcode, id=".arrayPush", reftext="arrayPush"]
=== .arrayPush(collection, key, data)

Adds data onto arrays in an existing database entry.

NOTE: If the data you attempt to push onto an array is already present, it will not be added again.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key for the database entry.
* `data` – _Any_, key-value pairs of arrays and the entries to add to them.

==== Returns

(Async) _Boolean_, indicates whether the data was successfully added to the specified arrays.

==== Example

[source, javascript]
const isAdded = await database.arrayPush('myCollection', 'myExistingKey', {'myArray1':'myValue1', 'myArray2': 'myValue2'});

[.hcode, id=".arrayRemove", reftext="arrayRemove"]
=== .arrayRemove(collection, key, data)

Removes data from arrays in an existing database entry.

==== Parameters

* `collection` – _String_, name of the collection
* `key` – _String_, key for the database entry.
* `data` – _Any_, key-value pairs of arrays and the entries to remove from them.

==== Returns

(Async) _Boolean_, indicates whether the data was successfully removed from the specified arrays.

==== Example

[source, javascript]
const isRemoved = await database.arrayRemove('myCollection', 'myExistingKey', {'myArray1':'myValue1', 'myArray2': 'myValue2'});

[.hcode, id=".beginTransaction", reftext="beginTransaction"]
=== .beginTransaction()

Creates a new transaction for sending one or more updates to the database in a batch.

include::../../docs/_includes/databaseNote.adoc[tag=transaction]

==== Example

[source, javascript]
database.beginTransaction();

[.hcode, id=".commitTransaction", reftext="commitTransaction"]
=== .commitTransaction()

(Async) Submits a batch of update requests to the database in a single transaction.

include::../../docs/_includes/databaseNote.adoc[tag=transaction]

==== Example

[source, javascript]
await database.commitTransaction();

[.hcode, id=".delete", reftext="delete"]
=== .delete(collection, key)

Deletes an entire entry from the database.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key of the database entry.

==== Returns

(Async) _Boolean_, indicates whether the entry was successfully deleted.

==== Example

[source, javascript]
const isDeleted = await database.delete('myCollection', 'myExistingKey');

[.hcode, id=".generateSignedUploadRequest", reftext="generateSignedUploadRequest"]
=== .generateSignedUploadRequest(fileName)

Generates a signed URL for uploading a file directly to your project’s CDN.
For an in-depth guide to this method, see <<frontend-uploading#>>.

NOTE: The size limit for this method is 150MB per uploaded file.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `fileName` – _String_, name of the file to upload.

==== Returns

(Async) `SignedUploadRequest`, structured data of the signed request with the following structure:

[source, typescript]
----
interface SignedUploadRequest {
  url: string,
  signedRequest: {
    url: string,
    fields: {[index: string]: string};
  };
}
----

==== Example

[source, javascript]
const signedUpload = await database.generateSignedUploadRequest("fileName");

[.hcode, id=".get", reftext="get"]
=== .get(collection, key)

Gets the specified database entry or collection of entries.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – (Optional) _String_, key of the database entry.

==== Returns

(Async) _Object_, the requested values from the collection.

==== Example

[source,javascript]
----
const myData = await database.get('myCollection');
const myValue = await database.get('myCollection','myKey');
----

[.hcode, id=".getAll", reftext="getAll"]
=== .getAll(collection, keys)

Gets all the specified database entries.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `collection` – _String_, name of the collection.
* `keys` – Array of _Strings_, list of keys of the database entries to retrieve.

==== Returns

(Async) Array of _Objects_, the requested database entries from the collection.

==== Example

[source, javascript]
const myValue = await database.getAll('myCollection',['myKey1', 'myKey2']);

[.hcode, id=".getAllWhere", reftext="getAllWhere"]
=== .getAllWhere(collection, predicateKey, predicateOperation, predicateValues)

Gets all the database entries that match a query against a list of possible values.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `collection` – _String_, name of the collection.
* `predicateKey` – _String_, key of the data to query.
* `predicateOperation` – _String_, operator to use for the query. Possible values are `<`, `\<=`, `==`, `>`, `>=`.
* `predicateValues` – Array of _Strings_, list of values to run the query against.
Database entries need to match *one or more* of these values to be returned.

==== Returns

(Async) Array of _Objects_, database entries that match the queries of *at least one* predicateValue.

==== Example

[source, javascript]
const results = await database.getAllWhere('myCollection','predicateKey', '==', ['predicateValue1', 'predicateValue2']);

[.hcode, id=".getCollections", reftext="getCollections"]
=== .getCollections()

Gets a list of all collections available in the database.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Returns

(Async) Array of _Strings_, list containing the names of the collections.

==== Example

[source, javascript]
const collections = await database.getCollections();

[.hcode, id=".getWhere", reftext="getWhere"]
=== .getWhere(collection, predicateKey, predicateOperation, predicateValue)

Gets all the database entries that match a query against a value.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `collection` – _String_, name of the collection.
* `predicateKey` – _String_, key of the data to query.
* `predicateOperation` – _String_, operator to use for the query. Possible values are `<`, `\<=`, `==`, `>`, `>=`.
* `predicateValue` – _String_, value to run the query against.

==== Returns

(Async) Array of _Objects_, list of the database entries that match the query.

==== Example

[source, javascript]
const results = await database.getWhere('myCollection','predicateKey', '==', 'predicateValue');

[.hcode, id=".search", reftext="search"]
=== .search(collection, searchAttribute, searchValue)

Returns all the database entries where the value of `searchAttribute` partially matches `searchValue`.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `collection` – _String_, name of the collection.
* `searchAttribute` – _String_, key to partially match against.
* `searchValue` – _String_, value for the partial match.

==== Returns

(Async) Array of _Objects_, list of database entries that have a partial match.

==== Example

[source, javascript]
const results = await database.search('myCollection','myKey', 'myValue');

[.hcode, id=".set", reftext="set"]
=== .set(collection, key, value)

Adds an entry to the database.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key of the database entry.
* `data` – _Any_, key-value pairs to add to the database.

==== Returns

(Async) _Boolean_, indicates whether the entry was successfully added.

==== Example

[source,javascript]
----
const isAdded = await database.set('myCollection', 'myKey', {'myValue':1});
----

[.hcode, id=".update", reftext="update"]
=== .update(collection, key, data)

Updates an entry in the database with the given value.

NOTE: This method updates only the values specified in `data`. If additional values exist for the key, they are not changed.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key for the database entry.
* `data` – _Any_, key-value pairs to update on the value.

==== Returns

(Async) _Boolean_, indicates whether the update was successful.

==== Example

[source, javascript]
const updated = await database.update('myCollection',"myKey", {"myValue":2});

[.hcode, id=".uploadFile", reftext="uploadFile"]
=== .uploadFile(path, filename, mimetype)

WARNING: **Deprecated.** Use <<#.generateSignedUploadRequest>> for new and upgraded templates.

Uploads files to your project's CDN.
For example, images, profile pictures, and audio.

NOTE: The size limit for this method is 10MB per uploaded file.

include::../../docs/_includes/databaseNote.adoc[tag=immediate]

==== Parameters

* `path` – _String_, path to the file.
* `filename` – (Optional) _String_, name for the uploaded file.
* `mimetype` – (Optional) _String_, content type of the file.

==== Returns

(Async) _String_, Unique URL on `images.koji-cdn.com` or `objects.koji-cdn.com`, depending on the type of file.

NOTE: To prevent collisions, the specified filename is automatically modified to include a random string.

==== Example

[source,javascript]
const uploadedUrl = database.uploadFile(path, filename, mimetype);

== Related resources

* https://github.com/madewithkoji/koji-database-sdk[@withkoji/database on Github]
* https://www.npmjs.com/package/@withkoji/database[@withkoji/database on npm]
* <<vote-counter-blueprint#>>
* <<koji-database#>>
