= @withkoji/database
:page-slug: withkoji-database-package

Each Koji project includes a key-value store that you can use as a backend database for simple use cases, such as collecting information from users, aggregating survey or poll results, and creating leaderboards for games.

The @withkoji/database package enables you to
//tag::description[]
implement a Koji database for the backend of your template.
//end::description[]

== Install

Install the package in the backend service of your Koji project.

WARNING: To maintain adequate read/write security, your template must connect to the database only from a backend route.

[source,bash]
----
cd backend
npm install --save @withkoji/database
----

Your access credentials are automatically configured from environment variables.

== Database

[.hcode, id="new Database", reftext="new Database"]
=== new Database()

Instantiates `Database`.

==== Example

[source,javascript]
----
import Database from '@withkoji/Database';
const database = new Database();
----

== Database methods

[.hcode, id=".arrayPush", reftext="arrayPush"]
=== .arrayPush(collection, key, value)

Adds data onto arrays in an existing database entry.

NOTE: If the data you attempt to push onto an array is already present, it will not be added again.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key for the database entry.
* `value` – _Any_, key-value pairs of arrays and the entries to add to them.

==== Returns

(Async) _Boolean_, indicates whether the data was successfully added to the specified arrays.

==== Example

[source, javascript]
const isAdded = await database.arrayPush('myCollection', 'myExistingKey', {'myValue':1});

[.hcode, id=".arrayRemove", reftext="arrayRemove"]
=== .arrayRemove(collection, key, value)

Removes data from arrays in an existing database entry.

==== Parameters

* `collection` – _String_, name of the collection
* `key` – _String_, key for the database entry.
* `value` – _Any_, key-value pairs of arrays and the entries to remove from them.

==== Returns

(Async) _Boolean_, indicates whether the data was successfully removed from the specified arrays.

==== Example

[source, javascript]
const isRemoved = await database.arrayRemove('myCollection', 'myExistingKey', {'myValue':1});

[.hcode, id=".delete", reftext="delete"]
=== .delete(collection, key)

Deletes an entire entry from the database.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key of the database entry.

==== Returns

(Async) _Boolean_, indicates whether the entry was successfully deleted.

==== Example

[source, javascript]
const isDeleted = await database.delete('myCollection', 'myExistingKey');

[.hcode, id=".generateSignedUploadRequest", reftext="generateSignedUploadRequest"]
=== .generateSignedUploadRequest(fileName)

Generates a signed URL for uploading a file directly to your project’s CDN.

==== Parameters

* `fileName` – _String_, name of the file to upload.

==== Returns

(Async) `SignedUploadRequest`, structured data of the signed request with the following structure:

[source, typescript]
----
interface SignedUploadRequest {
  url: string,
  signedRequest: {
    url: string,
    fields: {[index: string]: string};
  };
}
----

==== Example

[source, javascript]
const signedUpload = await database.generateSignedUploadRequest("fileName");

[.hcode, id=".get", reftext="get"]
=== .get(collection, key)

Gets the specified database entry or collection of entries.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – (Optional) _String_, key of the database entry.

==== Returns

(Async) _Object_, the requested values from the collection.

==== Example

[source,javascript]
----
const myData = await database.get('myCollection');
const myValue = await database.get('myCollection','myKey');
----

[.hcode, id=".getAll", reftext="getAll"]
=== .getAll(collection, keys)

Gets all the specified database entries.

==== Parameters

* `collection` – _String_, name of the collection.
* `keys` – Array of _Strings_, list of keys of the database entries to retrieve.

==== Returns

(Async) Array of _Objects_, the requested database entries from the collection.

==== Example

[source, javascript]
const myValue = await database.getAll('myCollection',['myKey1', 'myKey2']);

[.hcode, id=".getAllWhere", reftext="getAllWhere"]
=== .getAllWhere(collection, predicateKey, predicateOperation, predicateValues)

Gets all the database entries that match a query against a list of possible values.

==== Parameters

* `collection` – _String_, name of the collection.
* `predicateKey` – _String_, key of the data to query.
* `predicateOperation` – _String_, operator to use for the query. Possible values are `<`, `\<=`, `==`, `>`, `>=`.
* `predicateValues` – Array of _Strings_, list of values to run the query against.

==== Returns

(Async) Array of _Objects_, database entries that match the queries.

==== Example

[source, javascript]
const results = await database.getAllWhere('myCollection','predicateKey', '==', ['predicateValue1', 'predicateValue2']);

[.hcode, id=".getCollections", reftext="getCollections"]
=== .getCollections()

Gets a list of all collections available in the database.

==== Returns

(Async) Array of _Strings_, list containing the names of the collections.

==== Example

[source, javascript]
const collections = await database.getCollections();

[.hcode, id=".getWhere", reftext="getWhere"]
=== .getWhere(collection, predicateKey, predicateOperation, predicateValue)

Gets all the database entries that match a query against a value.

==== Parameters

* `collection` – _String_, name of the collection.
* `predicateKey` – _String_, key of the data to query.
* `predicateOperation` – _String_, operator to use for the query. Possible values are `<`, `\<=`, `==`, `>`, `>=`.
* `predicateValue` – _String_, value to run the query against.

==== Returns

(Async) Array of _Objects_, list of the database entries that match the query.

==== Example

[source, javascript]
const results = await database.getWhere('myCollection','predicateKey', '==', 'predicateValue');

[.hcode, id=".search", reftext="search"]
=== .search(collection, queryKey, queryValue)

Gets all the database entries that have a partial match on a particular key

NOTE: The `queryKey` must be set for all entries in your data.
If some entries have no value for that key, an error will occur.

==== Parameters

* `collection` – _String_, name of the collection.
* `queryKey` – _String_, key to partially match against.
* `queryValue` – _String_, value for the partial match.

==== Returns

(Async) Array of _Objects_, list of database entries that have a partial match.

==== Example

[source, javascript]
const results = await database.search('myCollection','myKey', 'myValue');

[.hcode, id=".set", reftext="set"]
=== .set(collection, key, value)

Adds an entry to the database.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key for the value.
* `value` – _Any_, key-value pairs to add to the database.

==== Returns

(Async) _Boolean_, indicates whether the entry was successfully added.

==== Example

[source,javascript]
----
const isAdded = await database.set('myCollection', 'myKey', {'myValue':1});
----

[.hcode, id=".update", reftext="update"]
=== .update(collection, key, value)

Updates an entry in the database with the given value.

==== Parameters

* `collection` – _String_, name of the collection.
* `key` – _String_, key for the database entry.
* `value` – _Any_, key-value pairs to update on the value.

==== Returns

(Async) _Boolean_, indicates whether the update was successful.

==== Example

[source, javascript]
const updated = await database.update('myCollection',"myKey", {"myValue":2});

[.hcode, id=".uploadFile", reftext="uploadFile"]
=== .uploadFile(path, filename, mimetype)

Uploads files to your project's CDN. For example, images, profile pictures, and audio.

NOTE: The size limit for this method is 10MB per uploaded file.

==== Parameters

* `path` – _String_, path to the file.
* `filename` – (Optional) _String_, name for the uploaded file.
* `mimetype` – (Optional) _String_, content type of the file.

==== Returns

(Async) _String_, Unique URL on `images.koji-cdn.com` or `objects.koji-cdn.com`, depending on the type of file.

NOTE: To prevent collisions, the specified filename is automatically modified to include a random string.

==== Example

[source,javascript]
const uploadedUrl = database.uploadFile(path, filename, mimetype);

== Related resources

* https://github.com/madewithkoji/koji-database-sdk[@withkoji/database on Github]
* https://www.npmjs.com/package/@withkoji/database[@withkoji/database on npm]
* <<vote-counter-blueprint#>>
