= @withkoji/analytics
:page-slug: withkoji-koji-analytics-sdk
:page-description: Package for tracking custom events in your Koji templates.

The @withkoji/analytics package enables you to
//tag::description[]
track custom events in your Koji templates.
//end::description[]
For example, track onClick events for the links and buttons in a Koji.

To view the analytics data for your published Koji, use the *Koji button* in the top right, and then go to **More > Manage this Koji > Analytics**.
You will see data for your custom events along with a standard set of built-in metrics, which are calculated from the Koji's access logs.

TIP: Analytics data is processed at frequent intervals throughout the day.
If you are testing the custom events in a published template and you don't see results at first, wait 10 minutes to account for data processing latency, and then check again.

== Install

Install the package in the frontend service of your Koji project.

[source,bash]
----
npm install --save @withkoji/analytics
----

== Analytics

Import the package in your application code.

[source,javascript]
----
import Analytics from '@withkoji/analytics';
----

== Analytics methods

[.hcode, id=".track", reftext="track"]
=== .track(event, payload)

Generates an analytics event with the specified name and data payload, if applicable.

==== Parameters

* `event` – _String_, name of the custom event.
* `payload` – _Object_, (Optional) list of custom key-value pairs to save with the event.

==== Example

[source,javascript]
----
Analytics.track('My Custom Event');
Analytics.track('Won game', { score: 120 });
----

== Related resources

* https://github.com/madewithkoji/koji-analytics-sdk[@withkoji/analytics on Github]
