= Setting up koji.json
:page-slug: game-iap-setting-up-koji-json
:page-description: Setting up koji.json and our remix values
:figure-caption!:

In this section, we will:

- Add the `In-App Purchase` entitlement, so Koji can register our product.
- Define a `price` value that can be customized during Remix.

== Entitlements

First, we need to let Koji know that our new game template is going to use `In-App Purchases`.

Open the file `koji.json`, located in the root of the project, and find the following section of code.

[source,json]
-------------
...

"entitlements": {
    "InstantRemixing": true,
    "InstantRemixingNativeNavigation": true,
    "FeedEvents": true,
    "CustomMetadata": {
        "enabled": true,
        "metadata": {
        "title": "{{remixData.title}}",
        "description": "How high can you stack them?"
        }
    }
},

...
-------------

The code defines an `entitlements` object, containing a number of properties.

Let's add a new property called `InAppPurchases`.
Modify `entitlements` as follows.

[source,json]
-------------
"entitlements": {
    "InstantRemixing": true,
    "InstantRemixingNativeNavigation": true,
    "FeedEvents": true,
    "CustomMetadata": {
        "enabled": true,
        "metadata": {
        "title": "{{remixData.title}}",
        "description": "How high can you stack them?"
        }
    },
    "InAppPurchases": {
        "enabled": true,
        "products": [
            {
                "sku": "extraLives",
                "name": "Extra Lives",
                "price": "{{remixData.price}}",
                "isConsumable": true
            }
        ]
    }
}
-------------

`InAppPurchases` is defined as an object, and it contains an array of products.
We're only selling one product -- extra lives -- so we have only one product in the array.
It's defined as follows.

[source,json]
-------------
{
    "sku": "extraLives",
    "name": "Extra Lives",
    "price": "{{remixData.price}}",
    "isConsumable": true
}
-------------

Here's a breakdown of the properties in the product:

* *sku* - the identifier we use to look up our product when the user makes a purchase.
* *name* - the product name that appears on the user's receipt.
* *price* - the price of our product in USD.
We set this to `{{remixData.price}}`, which means it will use our custom value.
We define this in the next step.
* *isConsumable* - a flag that is set to `true` to indicate that the user can purchase the product multiple times.

== Remix Data

Still inside `koji.json`, scroll down to the `remixData` object.
This is where we define our customizable values that users can modify when remixing the template.

Let's add a `price` property and set it to `0.1` for now:

[source,json]
-------------
"remixData": {
    ...
    "price": 0.1
  },
-------------

[NOTE]
In order for our product to be registered, we need to *publish from the web editor*
This will allow us to test our purchases from the http://developer.withkoji.com/docs/develop/testing-templates#_debugging_in_app_purchases[Debugger].
*The price value also needs to be greater than 0*.


[IMPORTANT]
If working *locally*, you need to push your changes and pull them into the web editor, then publish.
More info https://developer.withkoji.com/docs/publish/publish-locally-developed[here]

== Wrapping up

We now have our product and price set up.

In the <<game-iap-payment-menu#,next section>>, we'll create our Payment Menu UI component.