= Setting up koji.json
:page-slug: game-iap-setting-up-koji-json
:page-description: Setting up koji.json and our remix values
:figure-caption!:

In the first section of this tutorial, you will
// tag::description[]
add the In-App Purchase entitlement and define a `price` value that can be customized during Remix.
// end::description[]

By the end of this section, you should feel comfortable:

* Adding and modifying entitlements and remix values inside `koji.json`

== Forking the game template

Get started by cloning the Tower Stack game to your own project.

. Open the https://withkoji.com/~Svarog1389/3ej3[Tower Stack] game.
. {blank}
include::../../docs/_includes/remixNav.adoc[tag=all]
+
A copy of the project is created in your Koji account, and the *Project Details* page for your new project is displayed.
. Click *Open in Code Editor*.
+
The Koji editor opens with the game code loaded.

include::../../docs/_includes/tutorialEditorNote.adoc[tag=all]

== Entitlements

First, you need to let Koji know that your new game template is going to use `In-App Purchases`.

Open the file `koji.json`, which is located in the root of the project, and find the following section of code.

[source,json]
----
...

"entitlements": {
    "InstantRemixing": true,
    "InstantRemixingNativeNavigation": true,
    "FeedEvents": true,
    "CustomMetadata": {
        "enabled": true,
        "metadata": {
        "title": "{{remixData.title}}",
        "description": "How high can you stack them?"
        }
    }
},

...
----

The code defines an `entitlements` object, containing a number of properties.

Add a new property called `InAppPurchases`.
Modify `entitlements` as follows.

[source,json]
----
"entitlements": {
    "InstantRemixing": true,
    "InstantRemixingNativeNavigation": true,
    "FeedEvents": true,
    "CustomMetadata": {
        "enabled": true,
        "metadata": {
        "title": "{{remixData.title}}",
        "description": "How high can you stack them?"
        }
    },
    "InAppPurchases": {
        "enabled": true,
        "products": [
            {
                "sku": "extraLives",
                "name": "Extra Lives",
                "price": "{{remixData.price}}",
                "isConsumable": true
            }
        ]
    }
}
----

`InAppPurchases` is defined as an object, and it contains an array of products.
You're only selling one product -- extra lives -- so you only have one product in the array.
It's defined as follows.

[source,json]
----
{
    "sku": "extraLives",
    "name": "Extra Lives",
    "price": "{{remixData.price}}",
    "isConsumable": true
}
----

Here's a breakdown of the properties in the product:

* *sku* - the identifier used to look up the product when the user makes a purchase.

* *name* - the product name that appears on the user's receipt.

* *price* - the price of the product in USD.
This is set to `{{remixData.price}}`, which means it will use a custom value.
This will be defined in the next step.

* *isConsumable* - a flag that is set to `true` to indicate that the user can purchase the product multiple times.

== Remix Data

Still inside `koji.json`, scroll down to the `remixData` object.
This is where you define your customizable values that users can modify when remixing the template.

Add a `price` property and set it to `0.1` for now:

[source,json]
----
"remixData": {
    ...
    "price": 0.1
  },
----

[NOTE]
In order for the product to be registered, you need to *publish from the web editor*.
This will allow you to test your purchases from the <<testing-templates#_using_the_koji_debugger, Debugger>>.
*The price value also needs to be greater than 0*.


[IMPORTANT]
If working *locally*, you need to push your changes and pull them into the web editor, then publish.
Click <<publish-locally-developed, here>> for more info.

== Wrapping up

In this section, you have set up the product and price.

In the <<game-iap-payment-menu#,next section>>, you'll create the Payment Menu UI component.
