= Payment logic
:page-slug: game-iap-start-purchase
:page-description: Writing functions to handle our payment logic
:figure-caption!:

In this section, we will:

- Define the `onPurchase()` function.
- Define the `onPurchaseCancel()` function.
- Modify the template's original game over behavior.

== Defining the functions

Remember when we said that the `PaymentDialog` component would receive `onPurchase` and `onPurchaseCancel` function props?
Let's define those functions and pass them in.
Update `frontend/src/Components/View/index.js` as follows.

[source,javascript]
------------------
...
import PaymentDialog from './PaymentDialog'

...

const Component = (props) => {
    ...

    // Create a state hook to let us control 
    // when we should display our PaymentDialog
    const [showPaymentDialog, setShowPaymentDialog] = useState(false);

    ...

    // In case the user proceeds to the leaderboard
    const onPurchaseCancel = () => {
        setShowPaymentDialog(false);
        startScoreSubmission();
    }

    const onPurchase = async () => {
        // Initiating a purchase of "extraLives" product that we defined in koji.json entitlements
        const purchase = await Koji.iap.startPurchase('extraLives');

        // If the purchase object contains a receiptId
        // it means that the purchase was successful
        if (purchase.receiptId) {
            setShowPaymentDialog(false);
            emitEvent('resumeGame');
            emitEvent('resetLives');


            // Submit the score just to have some backup in case
            // the player closes the game before submitting later
            if (dataManager.name !== "") {
                await dataManager.submitScore(score);
            }
        }
    }

    return(
        <Container>
            ...

             {showPaymentDialog &&
                <PaymentDialog 
                    onPurchase={onPurchase}
                    onPurchaseCancel={onPurchaseCancel}
                />
            }
        </Container>
    )
}
------------------

The `onPurchaseCancel()` function simply closes the menu and proceeds to the score submission process.

The `onPurchase()` function does a couple of things.

* First, it calls `Koji.iap.startPurchase('extraLives')`.
This initializes the purchase process and opens the payment dialog for our product.

** `extraLives` is the `sku` value we set in the `InAppPurchase` entitlement object at the beginning of this tutorial.

* If the transaction is successful, the returned `purchase` object will contain a `receiptId` property, and we can proceed with our Payment flow.

** Disable `PaymentDialog` by setting the state hook to false.

** Emit the `resumeGame` event, which is already defined.

** Emit the `resetLives` event, which we'll have to define later, since it wasn't included with the template.

** Submit the score if the player has already submitted their name.
This is optional, but a good thing to have if they happen to close the tab while playing.
In that case, we'll at least have the latest score saved.

[NOTE]
This use case does not require any backend validation.
We simply proceed with the flow if the purchase was successful.
If you wanted to save some data and later check if the user has already purchased something, you would need to check for receipts on the backend. But we'll leave that for another tutorial.

If you've already saved the file, then you probably got a crash, because we're missing the `startScoreSubmission()` function. Let's fix that.

== Modifying the `onGameOver()` function

The `onGameOver()` function is already defined in `frontend/src/Components/View/index.js`.
It triggers automatically when the game ends.

Find `onGameOver()`, which looks like this.

[source,javascript]
------------------
const onGameOver = async (data) => {
    setScore(data.detail.score);
    if (dataManager.name === "") {
        setTimeout(() => {
            setShowNameDialog(true);
            setGameView(GAME_VIEW.MAIN_MENU);
        }, 3000);
    } else {
        await dataManager.submitScore(data.detail.score);

        setTimeout(() => {
            setGameView(GAME_VIEW.MAIN_MENU);
            setShowLeaderboard(true);
        }, 3000);
    }
}
------------------

Extract the conditional part of `onGameOver()` into a separate `startScoreSubmission()` function, and then modify the results to match the following.

[source,javascript]
------------------
const onGameOver = async (data) => {
    setScore(data.detail.score);

}

const startScoreSubmission = async () => {
    if (dataManager.name === "") {
        setShowNameDialog(true);
        setGameView(GAME_VIEW.MAIN_MENU);
    } else {
        await dataManager.submitScore(score);

        setGameView(GAME_VIEW.MAIN_MENU);
        setShowLeaderboard(true);
    }
}
------------------

There are *two important things* to notice about the new `startScoreSubmission()` function.

1. The two `setTimeout` handlers have been removed.
We no longer need a delay before displaying the game over screen and moving to score submission, because that transition is now triggered by user action.

2. The argument we're passing to `submitScore()` has changed from `data.detail.score` to just `score`.
Originally, `submitScore()` was called inside `onGameOver()`, so it could get the score from the data object that was passed as an argument to `onGameOver()`.
But since `startScoreSubmission()` doesn't accept any arguments, `submitScore()` now has to get the score from the variable that's set by the state hook.

Lastly, let's update `onGameOver()` to behave appropriately based on whether or not we have the price.

[source,javascript]
------------------
const onGameOver = async (data) => {
    setScore(data.detail.score);

    const price = Number(Koji.remix.get().price);

    if (price > 0) {
        setShowPaymentDialog(true);
        emitEvent('pauseGame');
    } else {
        startScoreSubmission();
    }
}
------------------

First, we get the price from `remixData` and make sure it's a number.

If there is a price, we show `PaymentDialog`.
Otherwise, we go straight to score submission and leaderboard.

== Wrapping up

*Congratulations, that was the hardest part!*

We've created a Payment flow, which can be tested with the http://developer.withkoji.com/docs/develop/testing-templates#_debugging_in_app_purchases[Debugger].
Nothing happens in the game itself just yet, though.

In the <<game-iap-updating-game#,next section>>, we'll dig into the game code and make it respond to our payment.