= Updating game behavior
:page-slug: game-iap-updating-game
:page-description: Updating your game to respond to payment
:figure-caption!:

In the <<game-iap-start-purchase#,previous section>> of the in-app purchases game tutorial, you've created a Payment flow for the game.
In this section, you’ll
// tag::description[]
modify the template's original behavior to reflect the new flow.
// end::description[]

By the end of this section, you should feel comfortable:

* Adding a listener for the `resetLives` event

* Modifying game elements to reflect the new flow

* Testing the game to make sure everything works correctly

== Adding a listener for the resetLives event

This template uses CustomEvents to communicate between the game instance and the main component, so it's a good idea to respect that in the workflow.

You've already added the `emitEvent(resetLives);` call inside the `onPurchase()` function, so now you need to add a listener for it.

If you go to `frontend/src/Components/Game/index.js`, you'll find that there are already some listeners defined in the first `useEffect` hook.
This is where you'll define your new one.

`window.addEventListener('resetLives', resetLives);`

Also make sure to remove it inside the `return` function, so that it gets deleted when the game component unmounts.
This is important for preventing memory leaks.

`window.removeEventListener('resetLives', resetLives);`

[source,javascript]
----
useEffect(() => {
    if(game){
        game.players = props.players;
    }
}, [props.players])

return (
    <Container>
        <div id={'p5game'} />
        <Loader id={"p5_loading"}><Spinner /> </Loader>
    </Container>
)
----

You also need to define the callback function that we're passing to the listener.

[source,javascript]
----
...
import { spawnFloatingText } from './Effects/FloatingText';
...

const resetLives = () => {
    game.lives = game.startingLives;
    game.gameOver = false;

    spawnFloatingText("EXTRA LIVES", game.width / 2, game.height / 2, {
        duration: 1,
        maxSize: 45
    });
}
----

Here, you do the actual reset of lives.
Additionally, you make sure to reset the `game.gameOver` property to `false` and also spawn some floating text in the middle of the screen to celebrate this wholesome event.

If you've gone through my <<game-intro#,Creating a remixable game>> tutorial or are already familiar with this game template, you could get even more creative and spawn some *exploding particles*!

The player just spent some cash on the game -- they should be rewarded.

== Modifying Block.js

In the original game, once all lives are lost, the game "camera" returns to the bottom.
This feature is not needed now, so it can be disabled.

Inside `frontend/src/Components/Game/Entities/Block.js`, find the `handleMiss()` function.
It looks like this.

[source,javascript]
----
handleMiss() {
    this.hasMissed = true;
    playSound(game.sounds.loselife);

    const distanceFromPreviousBlock = Math.abs(this.pos.x - game.blockDesiredX);
    if (distanceFromPreviousBlock < this.size) {
        this.rotDir = Math.sign(this.pos.x - game.blockDesiredX);
        this.isRotating = true;
    }

    setTimeout(game.loseLife, 400);
    setTimeout(() => {
        if (game.gameOver) {
            moveToStart();
        }
    }, 500);
}
----

You want to remove the last part that gets it back to the start, so the final result should look as follows.

[source,javascript]
----
handleMiss() {
    this.hasMissed = true;
    playSound(game.sounds.loselife);

    const distanceFromPreviousBlock = Math.abs(this.pos.x - game.blockDesiredX);
    if (distanceFromPreviousBlock < this.size) {
        this.rotDir = Math.sign(this.pos.x - game.blockDesiredX);
        this.isRotating = true;
    }

    setTimeout(game.loseLife, 400);
}
----

=== Removing the original Game Over text

Since the new `Game Over` text shows up in a new menu, you don't need the original one where the label would slide down from the top.

You can disable it by going into `frontend/src/Components/setup.js` and, inside the `game.loseGame()` function, removing these two lines.

[source,javascript]
game.ui.instructionsAnimTimer = 0;
game.ui.instructionsFadeOutTimer = game.instructionsFadeOutDuration;

So the whole function should look like this.

[source,javascript]
game.loseGame = () => {
    game.lives = 0;
    game.gameOver = true;
    game.ui.instructionsAnimTimer = 0;
    game.ui.instructionsFadeOutTimer = game.instructionsFadeOutDuration;
    emitEvent('gameOver', { score: game.score });
}

That was all you needed to do acommodate your game to the new way of doing things!

== Testing The Game

To test the new `In-App Purchase` feature, you can use http://developer.withkoji.com/docs/develop/testing-templates#_debugging_in_app_purchases[Koji Debugger] (you'll need to have some balance in your Koji Wallet for this), or you can temporarily disable the payment process and just emit the `resetLives` event directly, as follows.

[source,javascript]
----
const onPurchase = async () => {
    // Comment this for testing, skip the check
    //const purchase = await Koji.iap.startPurchase('extraLives');

    //if (purchase.receiptId) {
        setShowPaymentDialog(false);
        emitEvent('resumeGame');
        emitEvent('resetLives');

        // Submit the score just to have some backup in case
        // the player closes the game before submitting later
        if (dataManager.name !== "") {
            await dataManager.submitScore(score);
        }
    //}
}
----

[NOTE]
Make sure to *uncomment* those lines before publishing.

== Wrapping up

In this section, you've modified the template's original behavior to reflect the new flow, which concludes the main part of the experience.

In the <<game-iap-remix#,last section>>, you'll make the price customizable during Remix.
