= Quick start
:page-slug: adv-quick-start
:page-description: Instructions to quickly start coding your first project.
:includespath: ../_includes


Welcome to Koji!

This quick start topic guides you through creating your first project in the Koji IDE and developing your first Koji app.
You must be comfortable with developing web applications.

* If you are new to Koji and have minimal or no web development experience, go through <<quick-start#, the Getting Started tutorial>> instead.
* If you prefer to work locally, follow the <<work-locally#,Working locally>> instructions.


== Prerequisites

* https://withkoji.com/[A Koji account]


== Getting started with Koji

. To create a project, fork an existing scaffold or any project that allows forking.
+
.Step details ...
[%collapsible]
====
.. Go to the https://withkoji.com/create/for-developers[For Developers] page.
.. Choose a scaffold and click *View*.
.. In the scaffold's detail page, click the ellipses icon ( *...* ) and choose *Fork*.
====

. Develop your app.
.. In the Project Details page, rename your new project, then open it in the Koji code editor. +
Learn more: <<editor#_opening_a_project_in_the_koji_code_editor,Opening a project>>
.. Edit your source files.
+
TIP: You can find your source files in the navigation pane under *Source Code*.
+
... (Optional) If you chose a scaffold that still uses deprecated packages, migrate your project to use the @withkoji/core package. +
Learn more: <<migrate-koji-core#_do_i_need_to_migrate,Do I need to migrate?>>

... Update `koji.json` with your app's configuration settings.
+
include::{includespath}/koji-config.adoc[tag=koji-json-contents]
+
.Example of a `koji.json` file
[source,JSON]
----
include::../_includes/koji.json[]
----

... Develop the *Default* context of your app. +
This is the primary page that your users would see and interact with.
* Develop the front end of the context.
+
.... Install the @withkoji/core package in the frontend.
+
[source, Bash]
npm install @withkoji/core

.... Import the package in your frontend code.
+
[source,Javascript]
import Koji from '@withkoji/core';

.... Use the `Koji.config` function to initialize the package with your configuration data.
+
Ideally, your code will initialize the package one time, before any data in the application is rendered.
For example:
+
[source,Javascript]
----
// Initialize
Koji.config(require('././koji.json'));

// render
render();
----

.... Add functionality to your app using the front-end APIs. +
Learn more: <<core-frontend-overview#>>

* (Optional) Develop the back end of the context.
+
.... Install the @withkoji/core package in the backend.
+
[source, Bash]
npm install @withkoji/core

.... Make sure the `koji.json` file will be bundled with the backend service during deployment.
+
In most frameworks, this file won’t be bundled by default because it is not in the same folder as the backend code.
If the file is not bundled, the backend service will not be initialized correctly and the deployment will fail.
To solve this problem, you can use a tool such as https://www.npmjs.com/package/babel-plugin-inline-json-import[babel-plugin-inline-json-import].
.... Import the package in your backend code.
+
[source,Javascript]
import { KojiBackend } from '@withkoji/core';

.... Use `KojiBackend.middleware` to initialize the package with your configuration data.
+
The middleware manages the scope for backend functionality, so that your code can support your initial Koji along with all of its remixes.
It works by parsing the request headers that the Koji platform uses to pass remix-specific data to the backend.
+
You must apply this middleware before handling any routes.
The middleware will transform `res.locals`, and then modules in KojiBackend will accept `res` as a configuration parameter.
For example, here is an implementation with a traditional express application.
+
[source,Javascript]
----
import cors from 'cors';
import express from 'express';
import bodyParser from 'body-parser';
import { KojiBackend } from '@withkoji/core';

// Import our configuration
import kojiConfig from '../../koji.json';

// Init
const app = express();

// Enable cors for preflight
app.options('*', cors());

// Whitelist all routes with cors
app.use(cors());

// Use express json
app.use(express.json());

// Parse application/json
app.use(bodyParser.json());

// Koji Middleware
app.use(KojiBackend.middleware(kojiConfig));

// Disable caching
app.use((req, res, next) => {
  res.header('Cache-Control', 'private, no-cache, no-store, must-revalidate');
  res.header('Expires', '-1');
  res.header('Pragma', 'no-cache');
  next();
});

// Add our routes here

// Start server
app.listen(process.env.PORT || 3333, null, async err => {
  if (err) {
    console.log(err.message);
  }
  console.log('[koji] backend started');
});
----

.... Add functionality to your app using the back-end APIs. +
Learn more: <<core-backend-overview#>>, <<add-service#>>, <<koji-database#>>

... (Optional) Develop other contexts or modes that your app needs.
+
.Optional contexts in Koji ...
[%collapsible]
====
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-remix]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-about]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-admin]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-receipt-seller]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-receipt-buyer]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-sticker]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-thumbnail]
====

. Test your app. +
Learn more: <<testing-templates#>>, <<template-checklist#>>

. Deploy your app. +
Learn more: <<editor#_publishing_your_koji,Publishing your Koji>>

TIP: You can later return to your list of projects by going to https://withkoji.com/developer/projects[your developer portal page].


== Related topics

* <<design-guidelines#>>
