= Quick start
:page-slug: adv-quick-start
:page-description: Instructions to quickly start coding your first project.
:includespath: ../_includes


Welcome to Koji!

This quick start topic guides you through creating your first project in the Koji IDE and developing your first Koji app.
You must be comfortable with developing web applications.

* If you are new to Koji and have minimal or no web development experience, go through <<quick-start#, the Getting Started tutorial>> instead.
* If you prefer to work locally, follow the <<work-locally#,Working locally>> instructions.


== Prerequisites

* https://withkoji.com/[A Koji account]


== Getting started with Koji

. To create a project, fork an existing scaffold or any project that allows forking.
+
.Step details ...
[%collapsible]
====
.. Go to the https://withkoji.com/create/for-developers[For Developers] page.
.. Choose a scaffold and click *View*.
.. In the scaffold's detail page, click the ellipses icon ( *...* ) and choose *Fork*.
====

. Develop your app.
.. In the Project Details page, rename your new project, then open it in the Koji code editor. +
Learn more: <<editor#_opening_a_project_in_the_koji_code_editor,Opening a project>>
.. Edit your source files.
+
TIP: You can find your source files in the navigation pane under *Source Code*.
+
... (Optional) If you chose a scaffold that still uses deprecated packages, migrate your project to use the @withkoji/core package. +
Learn more: <<migrate-koji-core#_do_i_need_to_migrate,Do I need to migrate?>>
... Install the @withkoji/core package.
+
TIP: To use the command line to install packages or to perform tasks, expand the terminal pane at the bottom.
+
Learn more: <<withkoji-koji-core#>>
... Update `koji.json` with your app's configuration settings.
... Develop the *Default* context of your app. +
This is the primary page that your users would see and interact with.
* Develop the front end of the context.
* (Optional) Develop the back end of the context. +
Learn more: <<add-service#>>, <<koji-database#>>
... (Optional) Develop other contexts or modes that your app needs. +
The following are the optional contexts in Koji:
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-remix]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-about]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-admin]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-receipt-seller]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-receipt-buyer]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-sticker]
* {blank}
include::{includespath}/contexts-modes.adoc[tag=context-type-thumbnail]

. Test your app. +
Learn more: <<testing-templates#>>, <<template-checklist#>>

. Deploy your app. +
Learn more: <<editor#_publishing_your_koji,Publishing your Koji>>

TIP: You can later return to your list of projects by going to https://withkoji.com/developer/projects[your developer portal page].


== Related topics

* <<design-guidelines#>>
