= Introduction to Koji
:page-slug: introduction
:figure-caption!:

Koji is a powerful Link in Bio service.
It is used by artists, influencers, brands, and content creators everywhere to monetize, engage, and grow their audiences.

== Develop apps that power the creator economy

As a developer on Koji, you can build apps that creators can customize and add to their Link in Bio profiles.
Koji apps are full-stack, modern JavaScript applications that are designed to run in webviews on all social platforms.
You can build any type of app – from premium content sales, to games and utilities – and your software can be used and shared by millions of people worldwide.

== The Koji developer experience

The Koji development platform offers everything you need to develop, deploy, and distribute your apps.

Get going quickly ::
+
To accelerate your development project, Koji provides developer scaffolds and apps with open-source code as starting points.
Simply fork one of these apps and start editing the code.
Leverage Koji technology ::
+
The @withkoji/core package lets you implement platform features, like push notifications, user management, in-app purchases, and backend databases.
It also provides straightforward methods for common functions, like capturing user input.
That means less boilerplate code and more time coding the unique parts of your app.
Leave the DevOps to Koji ::
+
The Koji platform has built-in infrastructure to handle your app development and deployment.
You get integrated source control, development and staging environments, preview and debugging tools, a CI pipeline, hosting, and more.
Distribute your apps to a marketplace ::
+
Reach a vibrant community of content creators by listing your app on the App Store.
Or, share a direct link to your app with your collaborators and customers.
Monetize your work ::
+
Make money by setting a price for creators to use your app.
Or, add in-app purchases and earn 60 percent of the transaction fees on each completed purchase.

== Get started

For help starting your app on Koji, check out these resources:

* <<start-tutorial#>> – Step-by-step tutorial for learning fundamental concepts and developing your first project on Koji.
* <<withkoji-koji-core#>> – Package reference for implementing core platform features in your apps.
* https://withkoji.com/create/for-developers[Developer scaffolds in the App Store] – Starting points for an entirely new web app on Koji.

== What's new for developers

For the latest updates to the Koji platform, packages, and developer site, check out the <<developer-updates#>>.

== Stay in touch

* Join the https://discord.com/invite/9egkTWf4ec[Koji community] on Discord to connect with other developers, creators, and the Koji team.
The community is the best place to share tips and tricks, provide peer feedback, and get support.
* Check out the https://help.withkoji.com/[Koji Help Center] for answers to general questions about Koji.
* Use the *chat icon* to log an issue or request directly with the Koji team.
It's available in the bottom-right corner of the https://withkoji.com[Koji home page], the https://withkoji.com/apps[Koji App Store], and the https://blog.withkoji.com/[Koji Blog].
* <<contribute-koji-developers#,Contribute to the developer site>> by coding, writing new articles, or suggesting edits to existing documentation.
* Subscribe to the http://eepurl.com/g5odab[developer email list] to keep up with the latest announcements, featured content, events, and developer programs.
