= Introduction to Koji
:page-slug: introduction

Koji is a platform that enables everyone, including everyday users, to quickly create interactive content, such as selfies, memes, games, and utilities.
Kojis can be shared via a link on social media and messengers as well as in an embedded iframe on a website.

As a developer, you can build web applications on Koji, called “templates,” that enable users to customize, or “remix,” them without coding.
At their core, Koji templates are embeddable, mini-web applications written in modern JavaScript.
They are designed to be responsive, so that they can run on any browser and every device.
They also enable non-technical users to quickly edit elements, such as images, text, and sounds, to create a custom version that they can share anywhere on the web.

On Koji, you can develop templates that will be used and shared by millions of users across the world.
You can also monetize your work through licensing, asset packs, and other developer compensation programs.
With the ability to create and share remixable, interactive content, the opportunities for creative new applications and experiences are countless.
We can’t wait to see what YOU make!

image:Koji-developer.svg[Overview of the Koji development process,title="Koji development process"]

== Getting Started

For some great resources to help you start developing templates on Koji, see:

* link:../gettingStarted/startGuide1.adoc[Starter guide] – Step-by-step instructions on how to create a remixable web application and publish it as a template on Koji.
* link:../videos/starterCourse.adoc[Starter course] – Video tutorial of how to start developing applications on Koji.

== Staying in Touch

Join the https://discord.gg/eQuMJF6[Koji community] on Discord to connect with other developers, makers, and the Koji team.
The community is the best place to share tips and tricks, provide peer feedback, and get support.

Subscribe to the http://eepurl.com/g5odab[developer email list] to keep up with the latest announcements, featured content, events, and developer programs.
