= Enabling plugins in your Koji template
:page-slug: enabling-plugins
:page-description: How to enable a plugin for your Koji template.

In the second starter guide, you learned how to add different types of customization options to your template.
In this part of the guide, you will learn how to add an additional feature by enabling one of the built-in plugins that are available to Koji users.

== Prerequisites

* Complete the <<start-guide-1#>> and <<start-guide-2#>>.
* Open your starter guide project in the Koji editor.

== Enabling a plugin

In this example, you will enable the *Custom Boilerplate* plugin, which displays a popup requiring users to agree to a statement before interacting with the Koji.

. Click *Open published app*.
. Use the Koji button at the top right, and then go to `More > Manage this Koji > Plugins`.
You should see a list of available plugins.
. Click *Custom Boilerplate* in the *Available* list.
. Click *Enabled*. This should toggle the setting on, enabling the plugin.
. Click *Body text* and enter a short statement that you want the user to agree to. Example: I acknowlege that I have read the directions.
. Click *Back*.
. Click *Button text* and enter text for the button. Example: I agree.
. Close all the dialog boxes.
. Refresh the webpage. If this is the first time you've run the Koji after enabling the plugin, a popup should appear prompting you to agree with the text you entered.



