= @withkoji/core Frontend
:page-slug: core-frontend-overview
:page-description: Overview of the @withkoji/core frontend module.

Exposes the Koji class, which provides client-side methods for use on the frontend of your Koji.

[NOTE]
====
* All methods in the frontend module are scoped for use only in frontend services of Kojis.
If a method is invoked in a node/backend environment, it returns an error message.
* Frontend modules do not require a constructor.
====

== Basic use

To use frontend methods, install the <<withkoji-koji-core#, @withkoji/core package>> in the frontend of your project.

Import the package in your frontend code.

[source,javascript]
import Koji from '@withkoji/core';

Initialize the package with your configuration data.

[source,javascript]
----
// Initialize
Koji.config(require('././koji.json'));

// render
render();
----

Indicate that the application is ready to start receiving events.

[source,javascript]
Koji.ready();

Enable the user to upload an image from the frontend of the Koji.

[source,javascript]
----
import Koji from '@withkoji/core';

const captureImage = async () => {
  const imageURL = await Koji.ui.capture.image();

  console.log(imageURL); // The publicly accessible, CDN-backed path of the user's uploaded image
}
----

== Properties

[id=".analytics", reftext="analytics"]
=== .analytics

_<<core-frontend-analytics#,Analytics>>_, Class that enables you to track custom events in your Koji template.

[id=".configInitialized", reftext="configInitialized"]
=== .configInitialized

_Boolean_, Indicates whether the package has been <<.config, initialized with configuration data>>.
Defaults to `false`.

[id=".dispatch", reftext="dispatch"]
=== .dispatch

_<<core-frontend-dispatch#,Dispatch>>_, Class that implements a dispatch system for real-time communication on the frontend of your Koji template.

[id=".iap", reftext="iap"]
=== .iap

_<<core-frontend-iap#,IAP>>_, Class that manages in-app purchase transactions on the frontend of your Koji template.

[id=".identity", reftext="identity"]
=== .identity

_<<core-frontend-identity#,Identity>>_, Class that manages authentication and authorization on the frontend of your Koji template.

[id=".isReady", reftext="isReady"]
=== .isReady

_Boolean_, Indicates whether the Koji is <<.ready, ready to start receiving events>>.

[id=".playerState", reftext="playerState"]
=== .playerState

_<<core-frontend-playerstate#,PlayerState>>_, Class that manages the context of the Koji to enable distinct experiences for different users and views.

[id=".projectId", reftext="projectId"]
=== .projectId

_String_, (Optional) Unique identifier for the Koji.

[id=".remix", reftext="remix"]
=== .remix

_<<core-frontend-remix#,Remix>>_, Class that manages the remixing experience for your Koji template.

[id=".services", reftext="services"]
=== .services

_<<Services>>_, Object that provides access to service endpoints in the Koji.
For example, you can use this property to route a request to a backend service.

==== Example

[source,javascript]
const backendURL = Koji.services.backend

[id=".ui", reftext="ui"]
=== .ui

_UI_, Class that provides common user interface elements for use in your Koji template.
Exposes the following classes:

* _<<core-frontend-ui-capture#,Capture>>_, Class that captures user input on the frontend of your Koji template.
* _<<core-frontend-ui-navigate#,Navigate>>_, Class that provides methods for controlling navigation within your Koji template.
* _<<core-frontend-ui-present#,Present>>_, Class that presents dialog boxes to users on the frontend of your Koji.

== Methods

[id=".config", reftext="config"]
=== .config(kojiConfig, kojiConfigOptions)

Initializes this package for use with configuration data from the `koji.json` file.
This method sets up the services, remix values, development environment, and deployment instructions for your Koji template.
It also performs some basic structural checks.

NOTE: A template should initialize the package one time, before any data in the application is rendered.

==== Parameters

* `kojiConfig` – _<<KojiConfig>>_, (Optional) Configuration data for the Koji.
* `kojiConfigOptions` – _<<KojiConfigOptions>>_, (Optional) Configuration options for the Koji.

==== Example

[source,javascript]
Koji.config(require('././koji.json'));


[id=".ready", reftext="ready"]
=== .ready()

Indicates that the Koji is ready to start receiving events.

NOTE: You must call this function after initializing the package and subscribing to remix state changes, but before advancing to the preview with `Koji.remix.finish`.

==== Example

[source,javascript]
Koji.ready();

== Interfaces

=== KojiConfig

Configuration data for the Koji.

==== Properties

* `@@initialTransform` – _Any_, (Optional) Placeholder values for new remixes.
* `deploy` – _Any_, (Optional) Instructions for deploying the services to production.
* `develop` – _Any_, (Optional) Instructions for setting up the services in a development/editor environment.
* `remixData` – _Any_, (Optional) Default values for the customizable remix data.

=== KojiConfigOptions

Configuration options for the Koji.

==== Properties

* `projectId` – _String_, (Optional) Unique identifier for the Koji.
* `services` – _<<Services>>_, (Optional) Defines services for the Koji.

== Type aliases

=== Services

_Object_, Key-value pairs of services and endpoints.
