= Glossary
:page-slug: glossary
:page-description: Definitions of Koji-related terms.
// Settings:
:experimental:
// Refs:
:includespath: ../_includes

entitlement::
Configuration settings that allow the template or Koji to use certain platform features, such as enabling remixing or defining product information for in-app purchases.

in-app purchase (IAP)::
A financial transaction made within a Koji.

Koji::
A mini web application that can be shared on all social platforms, embedded in any website, and sent via messengers and email.
Internally, a Koji is comprised of the associated template and the custom remix settings.
Learn more: <<introduction#>>

player chrome::
The round Koji button in the Koji player, typically displaying the user's profile picture. When clicked, the button opens the user menu.

remix::
The process of customizing a Koji or template.
Or the custom Koji resulting from a remix process.
Learn more: <<instant-remixing#>>

template::
The underlying web application that powers a Koji and its remixes.
Learn more: <<templates#>>


// DC-599
